who-hoo/algorithm-study

후/20220313.java
- 최소 이동 횟수를 구하는 문제이므로 깊이 우선 탐색(DFS)이 아닌 너비 우선 탐색(BFS)를 통해 접근하였습니다.
- 어찌 계산해야할지 모르겠는데... `O(N*M^2*8)`(N:테스트 케이스 개수, M:체스판 크기)일 것 같습니다. 
- 최악의 경우 모든 체스판 좌표(M*M)를 전부 방문하고, 방문한 체스판 좌표에서 8가지 경우의 수를 체크하기 때문입니다.
=> [후] 20220313 "백준 - 나이트의 이동" 풀이 제출

후/20220406.java
1. 주어진 전력망을 둘로 나누는 문제이므로 두 전력망의 송전탑 개수(n)의 차이는 n보다 차이보다 클 수 없으므로 정답(answer)을 n으로 초기화
2. 주어진 wires를 순회하며 전선을 하나 끊음
3. bfs를 이용하여 연결되어있는 전력망의 노드 개수를 count -> 한 전력망의 송전탑 개수(group)
4. |(n - group) - group|를 answer과 비교하며 더 적은 경우 answer를 갱신
- 첫 풀이는 이렇게 구하지 않았고 배열에 송전탑 개수의 차이를 저장해두고, 마지막에 배열을 한번 탐색하며 최소값을 찾았었는데 접근방법을 적으면서 개선점이 떠올라서 개선하였습니다ㅎㅎ
6. 끊었던 전선을 다시 연결(2로 돌아가 주어진 wires를 끝까지 순회할 때까지 반복)
메이비 n^2...?! (주어진 노드(n)에 연결된 노드들(최대 n)을 전부 탐색해야 하기에...?!)
=> [후] 20220406 "프로그래머스 - 전력망을 둘로 나누기" 풀이 제출

후/20220511.java
- 회의실을 최대한 많이 사용하려면 `회의실 사용 시간이 짧은 회의부터 배정`하면 될거라 생각했습니다.
- 회의실 사용 시간(회의 종료시간 - 회의 시작시간)의 오름차순으로 정렬하여 배정 가능 여부를 판단하며 카운팅하였습니다.
- 애초에 로직이 틀리기도 했고, 회의를 별도의 클래스를 정의하여 사용해서 그런지 메모리 초과가 나기도 하였습니다ㅠ_ㅠ
- 기존의 로직이 틀렸다는건 알겠는데 그럼 도대체 어떻게 풀어야할지 모르겠어서 제리의 도움을 받았습니다.
- 키포인트는 회의실 사용 시간이 아닌 `회의 종료시간`으로, 회의 종료시간의 오름차순 다음으로 회의 시작시간의 오름차순으로 정렬하여 배정 가능 여부를 판단하며 카운팅하였습니다.
- 이 때, 배정 가능 여부는 직전에 배정한 회의 종료시간보다 지금 가능 여부를 판단하는 회의의 시작시간이 같거나 크면 가능한 것으로 판단합니다.
O(n log n)
제리의 브레인
메모리때문에 별도의 클래스를 정의하지 않고 풀어보고 싶었는데, 그럼 이차원 배열을 어떻게 정렬해야할지 모르겠어서 결국 Conference 클래스를 사용했네요ㅠㅠ 평소에 알고리즘 문제를 풀 때 커스텀 타입을 만들어 문제를 풀곤 하는데 이번에 제리에게 이것저것 조언을 많이 받으면서 이런 버릇을 고쳐야겠다는 생각이 들었습니다ㅠ_ㅠ
=> [후] 20220511 "백준 - 회의실 배정" 풀이 제출

후/20220608_1.java
1. 후보자 구조체 선언
- 후보자 번호
- 추천받은 횟수
- 순서(추천받은 횟수가 같을 때 더 오래된 후보자를 구분하기 위해)
3. 사진틀 리스트 선언(저는 연결리스트 사용했어요)
4. 추천수만큼 반복문 돌면서,
a. 이번에 추천받은 후보자가 이미 사진틀에 있으면, 그 후보자의 추천 횟수 +1
b. 이번에 추천받은 후보자가 사진틀에 없으면,
- 사진틀에 후보자를 추가할 수 있으면 -> 추가
- 없으면 사진틀 정렬(추천수의 내림차순으로 먼저 정렬 후, 순서의 내림차순으로 정렬)
- 리스트의 마지막 후보자와 새로운 후보자를 교체
5. 사진틀을 후보자 번호의 오름차순으로 정렬 후 출력
> 5. 사진틀을 후보자 번호의 오름차순으로 정렬 후 출력
이거 출력 조건을 제대로 안읽어서 왜맞틀 시전하느라 오래걸렸네요ㅠ_ㅠ 문제를 자세히 읽어야겠습니다 8ㅅ8
추천 횟수 * 사진틀의 수 * 사진틀의 수 log 사진틀의 수....?! ㅋㄷㅋㄷ
=> [후] 20220608 "백준 - 후보 추천하기" 풀이 제출

제리/20220607.java
구간 합을 구할 때 모든 인덱스를 돌며 더하면 시간이 오래걸리므로 입력값의 누적 합을 배열에 저장하여 입력받은 값을 토대로 뺄셈 연산 한 번으로 구간 합을 구할 수 있도록 했습니다.
=> 🔀 [제리] 20220607 "백준 - 구간 합 구하기 4" 풀이 제출

제리/20220726-01.java
문제 조건에 소수점 9자리까지만 체크한다고 되어 있어서 double로 해결이 가능했네요 :)
dfs를 통해서 지나갔던 길을 지나지 않고 n에 해당하는 깊이까지 이동했을 경우가 겹치지 않은 동선인 것을 활용해서 풀었습니다.
동쪽으로 이동하면 동쪽확률을, 서쪽이면 서쪽확률 ... 을 계속 sequence 배열에 저장하고 있다가 겹치지 않은 동선이면 sequence 배열에 있는 확률들을 곱해서 모든 경우의 확률을 구했습니다.
=> [제리] 20220726 "백준 - 미친 로봇" 풀이 제출

익조/20220314
처음에 DFS로 접근했다가 엄청난 시간 초과가 발생했었고 이러한 문제점을 어떻게 개선할 수 있을지 고민하다가 결국 BFS를 활용하여 접근하게 되었습니다. 하지만 막상 BFS로 접근하긴 했는데 처음 시작 위치에서 방문 처리 안 해줘서 무진장 헤맸네요..😂 딱 한 줄만 추가해줬으면 됐는데 결국 스스로 이걸 못 찾아냈고 마지막에 기술 블로그를 참고해서 발견할 수 있었습니다. 🤣 개인적으로 굉장히 아쉬웠던 문제였습니다. 그래도 뭔가 이 문제를 통해 오랜 시간 삽질을 겪음면서 우리 알고리즘 스터디의 숙원인 DFS와 BFS의 차이에 대해 조금은 느낄 수 있었던 것 같습니다.
음.. 정확하진 않지만 머리로 이해할 수 있는 정도로는 체스판의 좌표가 최대 300 * 300(=90,000)개 인데, 각 좌표별로 나이트의 이동 가능 경우의 수 8을 곱하여 O(300 * 300 * 8)이고, 여기에 테스트 케이스를 곱하는 게 시간 복잡도가 아닐까 싶었습니다. O(T * 300 * 300 * 8) ※ T는 테이트 케이스 수
=> [익조] 20220314 "백준 - 나이트 이동" 풀이 제출

후/20220816_2.java
이 문제 또한 접근 방법이 감조차 잡히지 않아 블로그 풀이를 참고하였습니다..
1. 오직 +, -로만 이동한 횟수로 초기 값 설정(버튼이 뭐가 고장났든 이동 가능한 유일한 방법)
2. 0~1000000까지 모든 채널을 숫자로 이동
2-1. 버튼이 고장나서 숫자 버튼으로 이동할 수 없는 경우는 pass
2-2. 숫자 버튼으로 이동 가능한 경우, 해당 해널에서 +, -를 이용하여 목표 채널로 이동한 후 최솟값 갱신
처음에 0~500000까지만 체크하면 된다고 생각해서 헤맸는데,,, 안풀려서 블로그 다시 봤습니다...
`500,000보다 큰 채널에서 접근하는 것이 어느 때는 더 최소 클릭일 수 있다`는 점에 유의해야겠습니다. 
백만 * 목표 채널의 자릿수(최대 6) = 6백만쓰?!
https://binux.tistory.com/44
=> 🔀 [후] 20220816 "백준 - 리모컨" 풀이 제출

아더/20220804.java
1. 처음엔 누적합으로 계산해보려고 시도했습니다. 입력받을 때 배열을 누적합으로 해놓고 계산하다보니 첫 번째 인덱스를 예외처리해줘야 하는 부분이 많아져서 배열 입력을 그대로 받고 처리했습니다.
2. 투포인터 개념을 사용했습니다. L인덱스와 R인덱스를 조작하며 합계가 기준을 넘을 때만 정답을 최솟값으로 갱신할 수 있도록 했습니다.
투포인터라 `O(N^2)` 보다는 작을 것 같습니다!
=> 🔀 [아더] 20220804 BOJ_1806_부분합 문제 풀이 제출

후/20220814.java
(1차시도) 완전 탐색으로 시도했으나 시간초과로 실패하였습니다.
동빈나의 투포인터, 부분합 강의를 보고 다시 재도전해보았습니다!
1. 시작점과 끝점을 첫 번째 원소의 인덱스로 설정
2. 현재 부분 합이 S이상이라면 시작점과 끝점 사이의 길이를 구하여 최소값을 갱신한다.
3. 현재 부분 합이 S보다 작다면 end를 1 증가시킨다.
4. 현재 부분 합이 S보다 크다면 start를 1 증가시킨다.
5. 모든 경우를 확인할 때까지 2번부터 4번까지의 과정을 반복한다.
O(N)
https://www.youtube.com/watch?v=rI8NRQsAS_s
=> 🔀 [후] 20220814 "백준 - 부분합" 풀이 제출

익조/20220405.java
+ 우선 n = 2이거나 n = 3인 경우 결과값이 정해져있으므로 별도 if문으로 결과값을 반환하도록 했습니다.
+ BFS를 이용해 문제를 해결할 수 있었습니다.
+ BFS 탐색을 하기 앞서 우선 전력망 중 임의의 전선을 하나 끊도록 했고 해당 전력망에 대해 BFS 탐색하도록 했습니다.
+ 이때 BFS 탐색 시 Target이라는 구조체를 만들고 Queue를 활용하여 전력망들을 탐색하면서 연결되는 노드(Target의 노드들에 포함되는 노드)가 있으면 Queue에 add 시키고 방문 처리 시켜주도록 했습니다.
+ 전선을 자를 수 있는 모든 경우에 대해 위 작업을 반복하면서 송전탑의 개수의 차이가 최소인 경우를 구합니다.
https://ikjo.tistory.com/189
BFS DFS의 시간 복잡도는 어떻게 구해야할지 잘 모르겠습니다...😇
매번 DFS, BFS 등 그래프 탐색 문제를 풀 때마다 뭔가 아이디어는 있는데, 구현을 하는데 엄청난 삽질과 함께 많은 시간이 소요되네요...🤣 이는 물론 아직 제 실력이 미숙하기 때문인 것 같습니다.. 😥 시간도 쫓기고 정신적으로 압박을 받는 실전 코딩테스트에서 뚝딱뚝딱 구현할 정도 되려면 그래프 탐색 문제만 적어도 100~200문제는 풀어봐야 할 것 같습니다..😭
=> [익조] 20220405 "프로그래머스 - 전력망을 둘로 나누기" 풀이 제출

제리/20220906.java
다익스트라를 이용해서 풀었습니다.
간선의 개수가 1개 이상이라서 다익스트라의 구현부가 조금 달라 헷갈렸네요.
어떤 간선이 최소값인지 알 수 없어서 기존에는 `boolean[] visited`를 통해 한 번 거친 노드는 다시 체크하지 않았지만 현재는 간선의 개수가 여러개라서 한 번 거친 노드도 다시 체크하기 위해서 visited 배열 없이 다 확인하도록 했습니다.
=> 🔀 [제리] 20220906 "프로그래머스 - 배달" 풀이 제출

후/20220911.java
- 아직 풀지는 못했지만, 지난번 쿼드 압축 후 개수 세기라는 문제를 풀면서 `분할 정복 알고리즘`이라는 키워드를 얻게 되어 해당 알고리즘을 이용하여 풀이하였습니다.
- 재귀를 이용하여 큰 배열을 작은 배열로 분할(4등분)하여 탐색하였습니다.
- [1차 시도](https://github.com/who-hoo/algorithm/commit/b74a998c3e68c741135d65ce285b5a11b423888d) : 처음에 입력받은 `N`을 이용하여 static 변수로 [N^2][N^2] 배열을 선언하여 전부 탐색, 방문한 후 array[r][c] 출력 -> `메모리 초과`
- [2차 시도](https://github.com/who-hoo/algorithm/commit/e98b65f9367dfa20134b50b97d6013e4499623a6) : 배열을 선언하는 대신, 순서값(sequence)만을 가지고 타겟(r, c)에 도달하면 해당 sequence를 출력하고 프로그램 종료 -> `시간 초과`
- 3차 시도(최종 코드) : @ikjo93 의 PR을 참고하여 찾고자 하는 지점(r, c)이 속하지 않은 구역은 재귀를 호출하지 않고, 순서값만 격자의 크기만큼 더하여 불필요한 연산을 생략할 수 있다는 것을 알게되었습니다. (언제나 저의 참고자료가 되어주시는 익조갓... 그저 빛✨)
흠냐링...
[이크조](https://github.com/who-hoo/algorithm-study/pull/424)
=> 🔀 [후] 20220911 "백준 - Z" 풀이 제출

아더/20220905.java
1. 먼저 다중집합을 구하기 위해 리스트를 두 개 선언하고 알파벳으로만 이루어진 집합들을 리스트에 추가했습니다.
2. 다음은 교집합을 구하는 부분인데 이 부분에서 엣지케이스를 잘 처리해줘야 했습니다. 단순히 하나의 집합원소에서 다른 집합에 존재하는지 판단하는 것이 아니라 존재한다면 원소를 지워주는 작업이 필요했습니다! (`str1 = "BAAAA", str2 = "AAA", answer = 32768`)
3. 합집합을 구할 땐 두 리스트의 합을 구한 뒤 교집합의 크기를 빼주는 것이 핵심입니다.
4. 마지막으론 다시 한 번 엣지케이스를 걸러주면 끝!(합집합이 0일 때 65536 리턴!)
`O(N^2)` 일듯요?
=> 🔀 [아더] 20220905 "프로그래머스 - 뉴스 클러스터링" 풀이 제출

익조/20221001.java
+ 해시와 브루트포스를 이용하여 해결할 수 있었습니다.
+ 초밥을 순차적으로 k개만큼 선택한 후 HashSet에 add한 후 추가로 c 쿠폰에 해당하는 초밥도 add하여,
+ 해당 HashSet의 크기를 최대값으로 초기화해주도록 했습니다. 이때 크기가 d와 동일하다면 더이상 탐색할 필요가 없으므로 탐색을 중단합니다.
+ 뭔가 해시를 이용하면 되겠다 생각하고 풀어봤는데, 알고보니 두 포인터를 이용한 문제였네요...ㅋㅋ (어쩐지 1초 넘게 나오더라..)
+ 두 포인터를 이용해서도 접근해보겠습니다. 😅
=> [익조] 20221001 "백준 - 회전 초밥" 풀이 제출

익조/20220929.java
+ 해쉬맵과 재귀를 이용하여 해결할 수 있었습니다.
+ 2개의 해쉬맵을 선언해주고, 하나는 판매자별 부모 판매자 정보를 저장해주었고, 또 다른 하나는 판매자별 이익을 저장해주었습니다.
+ 이후 판매자별로 판매한 칫솔 개수가 주어질 때마다 해당 판매자에게 돌아가는 이익과 수수료를 나누어, 수수료를 제외한 이익은 자기 자신에게 저장하고, 수수료는 부모에게 저장되도록 했습니다. 
+ 일련의 과정을 재귀 함수를 이용하여 좀 더 간단하게 로직을 작성해볼 수 있었습니다.
O(N * log h) ???
=> [익조] 20220929 "프로그래머스 - 다단계 칫솔 판매" 풀이 제출

제리/20221004-2.java
계속 조금씩 풀이가 제대로 되지 않아서 답을 참고했습니다.. 머리가 잘 안도네요 ㅠㅠ
초기에 k에 따라 회전 초밥에 존재하는 스시의 종류를 먼저 카운트 한 이후에 start 지점을 이동시키면서 계속 먹는 스시의 종류를 카운트했습니다.
카운트 할 때 스시의 종류에 쿠폰 번호에 해당하는 스시가 포함되어 있다면 그냥 두고 포함되어 있지 않다면 maxLen을 1 증가시켰습니다.
=> 🔀 [제리] 20221004 "백준 - 회전 초밥" 풀이 제출

후/20221004_2.java
1. 회전초밥벨트를 순회하며 시작인덱스부터 연속해서 먹는 접시의 수까지 Set에 초밥의 종류를 중복이 없도록 추가하였습니다.
2. 이 때, 원형연결리스트처럼 배열의 인덱스를 넘어가는 접시도 탐색하기 위해 나머지 연산자를 사용하고 쿠폰으로 먹는 접시는 미리 추가해두었습니다.
3. 연속해서 먹는 접시의 수만큼 추가가 끝나면, set의 사이즈를 이용하여 초밥종류의 최대값을 갱신해주고 set을 다시 초기화해주었습니다.
O(30,000 * 3,000)(벨트에 놓인 접시의 수(N)*연속해서 먹는 접시의 수(k))
=> 🔀 [후] 20221004 "백준 - 회전 초밥" 풀이 제출

익조/20220824.java
앗 2일전에 풀었던 문제네용..ㅋㅋ
+ https://ikjo.tistory.com/318
+ 주어지는 배열을 큐로 변환해서 풀었습니다.
+ 이후 두 큐의 합(sum1, sum2)을 구하고 sum1과 sum2를 비교하면서 같아질 때까지 디큐 및 엔큐를 해주면서 작업 횟수를 카운팅합니다.
+ 이때 처음 접근했었던 방법으로는 브루트 포스 방식으로 `sum1 = sum2일 수 있는` 모든 경우의 수를 따져줬었는데(결과는 시간 초과), 사실 그럴 필요도 없었던 게 앞선 디큐 및 엔큐 작업을 해주면서 가장 먼저 `sum1 = sum2` 조건을 만족한 경우의 작업 횟수가 `최소 작업 횟수`이기 때문입니다.
+ 이후 더 이상의 연산은 필요없으므로 무한 반복문에서 break시킵니다.
+ 아울러 처음에는 디큐 및 엔큐할 때마다 매번 큐를 순회하면서 합을 구해줬었는데, sum1과 sum2는 한번만 구하고 이를 변수에 담은 후 디큐, 엔큐되는 값들을 이 변수에 반영해주기만 하면, 굳이 매번 큐를 순회할 필요가 없게됩니다.
+ 어떤 방법으로도 각 큐의 원소 합을 같게 만들 수 없는 경우에 대해서도 고려(무한 반복문 탈출 조건 설정)해주어야 하는데, 이는 가장 오래 순회될 수 있는 길이를 찾아야합니다.
```
if q1과 q2의 길이가 5, then
q1 : _ _ _ x _  ->  _                  ->  _ _ _ _ _ _ _ _ _ 
q2 : _ _ _ _ _  ->  _ _ _ _ _ _ _ _ x  ->  x
최초            4번 작업                8번 작업   
위와 같이 최초 …
```
=> [익조] 20220824 "프로그래머스 - 두 큐 합 같게 만들기" 풀이 제출

동기/20221115.java
- 맵을 순회하기 위해 `bfs` 를 사용합니다
- 일반적인 2차원 boolean 배열을 사용하여 방문 체크를 하면 다음과 같은 문제가 발생하게 됩니다
- 벽을 한 번 부수고 이동하다 막다른 길이 나타나면 벽을 부수지 않는 다른 방향으로 시도해보아야합니다
- 2차원 boolean 배열을 사용하면 이미 방문 처리가 되었기 때문에 다른 방향으로 시도할 수 없게됩니다
- 그렇기 때문에 **벽을 부수지 않고 진행하는 케이스와 벽을 부수고 진행하는 케이스를 방문 처리 할 수 있는 boolean 배열을 선언합니다**
3차원으로 boolean 배열을 선언합니다
```java
// 2개의 n * m 방문 배열을 만들고 각각 0, 1은 벽을 부수지 않았을 때와 벽을 부쉈을 때 방문 처리를 합니다
boolean[][][] visited = new boolean[n][m][2];
```
- `Queue` 에 좌표를 넣어줄 때 벽을 부쉈는지 상태도 함께 넣어주도록 합니다
- 0, 0부터 맵을 순회할 때는 벽을 부수지 않았기에 벽을 부수지 않은 상태라는 의미로 0을 하나 더 넣습니다 `ex) q.offer(new int[]{0, 0, 0});`
- 다음 이동할 좌표가 벽이라면 `벽을 부순 적이 있는지 체크합니다
- 벽 부숨 상태가 0이라면 부순 적이 없으므로 해당 좌표를 방문할 수 있게됩니다
- 1번 방문 배열에 방문 처리를 해주고 이동한 거리를 업데이트 해줍니다
- 다시 `Queue` 에 좌표를 넣어줄 때는 벽을 한 번 부쉈기 때문에 벽 부숨 상태를 `1` 로 넣어줍니다 `ex) q.offer(new int[]{x, y, …
=> [동기] 20221115 백준 - 벽 부수고 이동(하)기 풀이 제출

익조/20220908.java
+ 문제에서 약간 대놓고(?) 재귀 힌트를 줘서 또한 지난번 `쿼드 압축 후 개수 세기` 문제를 푼 게 많은 도움이 되었습니다.
+ 지난번과 마찬가지로 재귀를 통해 전체 격자를 4등분으로 나누어 탐색하도록 했습니다.
+ 이때, 찾고자 하는 지점(r, c)이 속하지 않은 격자들은 재귀 호출하지 않도록 별도 if문으로 분기 처리해주었습니다.
+ 다만, 최종적으로 탐색한 횟수를 구해야하므로, 재귀 호출을 하지 않더라도 찾은 횟수는 그 격자의 크기만큼 더해주도록 합니다.
+ 최종적으로 목표 지점(r, c)을 찾으면 결과값 출력 후 프로그램을 종료 시켰습니다.
=> [익조] 20220908 "백준 - Z" 풀이 제출

루시드/20221129_1.java
=> [루시드] 20221129 백준 - 뱀과 사다리 게임 풀이 제출

익조/20220510.java
+ 문제에서 요구하고있는 `회의실을 사용할 수 있는 회의의 최대 개수`를 구하기 위해서는 우선 가장 일찍 시작하는 회의 시간에서 가장 늦게 시작하는 회의 시간 까지 겹치지 않으면서 사이사이에 가능한한 회의들이 다닥다닥 붙어있어야 합니다.
+ 이러한 환경(?)을 만들기 위해 우선 입력받은 회의실 정보를 '끝나는 시간'을 기준으로 오름차순 정렬하고 만일 같다면 '시작 시간'을 기준으로 오름차순 정렬합니다.
+ 이렇게 정렬한 후에 만일 첫 번째 회의의 끝나는 시간에 대해 두 번째 회의의 시작 시간이 같거나 크다면 이는 가장 연이어 할 수 있는 회의일 것입니다. 이후 이전과 같은 방법으로 두 번째 회의의 끝나는 시간에 대해  세 번째 회의의 시작 시간을 비교하여 동일한 작업을 반복해줍니다.
O(N * logN) → Collection.sort
=> [익조] 20220510 "백준 - 회의실 배정" 풀이 제출

익조/20220519.java
+ 문제 자체만 봤을 때 바로 DFS로 풀어야 겠다는 생각이 들었습니다.(또FS 소리 들을까봐 민망하군요..ㅋㅋ)
+ 깊이 우선 탐색을 통해 (0,0) 지점에서 출발했을 때 탐색할 수 있는 모든 경로에 대해 탐색이 끝났을 때 이동한 칸 수를 검사하여 모든 경로 중 가장 이동을 많이 한 횟수를 구하도록 했습니다.
+ 이 문제의 경우 기존 DFS랑 접근을 다르게 했었던 게 별도의 방문 처리는 하지 않았다는 점입니다. 왜냐하면 모든 경로에 대해 검사해야하기 때문에 방문처리를 하다보면 다른 경로의 탐색에 영향을 끼칠 수 있기 때문입니다. 사실 애초에 종료 조건 자체가 기존 보드판의 범위를 벗어나는 경우를 포함하여 `이미 밟은 알파벳을 또 밟을 경우`이기 때문에 다른 방법으로 탐색 종료를 해줄 필요가 있었습니다.
+ 이를 위하여 당초에는 HashMap을 사용하여 알파벳을 탐색할 때마다 해당 알파벳을 put해주고 기존에 밟았는지 여부를 containsKey 메서드를 이용하고자 했습니다. 하지만 HashMap의 경우 객체기 때문에 재귀 탐색 시 다른 경로들과 자료를 공유하는 이슈가 있었습니다. 그리하여 성능이 나쁘더라도 String 문자열 객체를 사용했습니다.
시간 제한을 over 했는데 일단 통과는 됐네요.. 시간복잡도를 개선할  수 있는 방법을 좀 더 생각해봐야 할 것 같습니당..
=> [익조] 20220519 "백준 - 알파벳" 풀이 제출

익조/20221204.java
+ 뭔가 DP 냄새도 살짝 났지만 처음엔 완탐으로 접근했다가 시간 초과나왔습니다 ㅠ
+ `~거리`하면 보통 DP 문제인 경우가 많더라구요.. ㅋㅋ
+ 하지만, N이 최대 1000이라 완탐으로 해볼만하다고 생각했었습니다...ㅋㅋ
+ 그래도 일단 완탐으로 접근하고나니 어느 연산에서 반복이 일어나는지를 파악할 수 있어 점화식을 세우기 용이했습니다 👍
+ 완탐 풀이도 공유해봅니다!!
```Java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.LinkedList;
import java.util.Queue;
class Main {
static int n, answer = Integer.MAX_VALUE;
public static void main(String[] args) throws IOException {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
n = Integer.parseInt(br.readLine());
String s = br.readLine(); // 0 : B, 1 : O, 2 : J
Queue<int[]> queue = new LinkedList<>();
queue.add(new int[]{0, 0, 0}); // 0 : 현재 위치, 현재 상태, 현재 에너지
while (!queue.isEmpty()) {
int[] pos = queue.poll();
for …
```
=> [익조] 20221204 "백준 - BOJ 거리" 풀이 제출

동기/20221209.java
- `Map` 을 이용하여 귤의 크기를 key로 하여 귤의 갯수를 저장합니다
- value 를 기준으로 내림차순 정렬하여 k개가 될 때까지 `Map` 에서 꺼내고 k개보다 적을 때까지 반복합니다
- 몇 가지의 귤을 상자에 담았는지 반환합니다
O(N)
=> [동기] 20221209 프로그래머스 - 귤 고르기 풀이제출

익조/20221031.java
+ 어렵네요..😅 아이디어 고민하다가 딱히 떠오르지 않아 풀이 봤읍니다...ㅋㅋ
+ 그래도 나름대로 `빨리 배송할 수 있는 것을 우선적으로 박스를 싣는게 최적의 해`라곤 생각은 해봤는데, 구현으로 이어지지 못했습니다. 💦
+ 트럭은 마을 1을 출발점으로 지나게 되는데, 이때 트럭의 용량은 한정적이기 때문에 최대한 마을 1로부터 가장 가까운 도착지의 박스들을 실어야 합니다.
+ 따라서 도착지가 가장 가까운 택배들을 기준으로 오름차순 정렬해준 후, 트럭 용량 내에 실은 후 순차적으로 다음 택배를 처리해주도록 했습니다.
O(MlogM) (오름차순 정렬)
=> [익조] 20221031 "백준 - 택배" 풀이 제출

익조/20220725.java
+ 해당 문제는 DFS를 통한 백트래킹을 이용하여 해결할 수 있었습니다.
+ 우선 로봇이 이동하는 평면을 나타내야되는데, 이 평면의 중심상에서 로봇이 출발하여 동, 서, 남, 북 방향으로 이동할 수 있도록 하는 것입니다. 이때 이러한 평면의 전체 크기는 n의 크기와 규칙이 있었습니다.
+ if n = 1, then 3 x 3 board
+ if n = 2, then 5 x 5 board
+ if n = 3, then 7 x 7 board ...
+ (2n + 1) x (2n + 1)
+ 이때 평면의 크기를 결정하는 것은 로봇이 평면 중심에서 하나의 방향으로만 이동했을 때의 거리입니다.
+ 이후 동, 서, 남, 북 방향별 확률을 HashMap을 이용하여 저장했는데, 백트래킹 시 이를 활용해 확률이 존재하는(0% 초과) 방향에 대해서만 탐색하도록 했습니다.
+ DFS를 통해 이동을 시작하는데, 이동할 때마다 해당 이동방향별 확률을 누적하여 곱해주었고, 탐색을 마치면(n번 이동을 마치면) 누적했었던 확률을 결과값에 더해주었습니다.
+ 참고로 탐색 시마다 방문처리를 해주기 때문에 최종 탐색을 마친 경우에는 `이동 경로가 단순한 경우`만 해당되게 됩니다.
+ 아래 블로그를 통해 DFS라는 키워드를 인지할 수 있었습니다.
+ https://jaimemin.tistory.com/724
=> [익조] 20220725 "백준 - 미친 로봇" 풀이 제출

익조/20220616.java
+  DFS를 이용하여 손님들이 주문한 메뉴들(String[] orders)로부터 구성 가능한 메뉴의 조합을 구합니다.
+ 이때 조합의 개수는 문제에서 주어지는 단품 메뉴 개수(int[] course)를 이용하여 정합니다.
+ HashMap을 이용하여 메뉴의 조합별 개수를 카운팅(counting))합니다.
+ 가장 많이 조합되었던 메뉴의 조합을 탐색합니다.
상세 : https://ikjo.tistory.com/195
※ 이 문제를 풀기 전에 루시드가 출제해줬던 로또 문제를 풀어본 것이 많은 도움이 됐었습니다 ㅎㅎ
=> [익조] 20220616 "프로그래머스 - 메뉴 리뉴얼" 풀이 제출
