후/20220213.java
저는 제가 고른 문제인데도 부끄럽지만...ㅎㅎ 스스로 풀이 방법을 떠올리지 못했습니다.
동기가 접근 방법을 설명해주셔서 같은 방법으로 `그리디` 알고리즘으로 접근해보았습니다.
1. 5로 나누어 떨어지는지 확인, 나누어 떨어지면 
2. 나누어 떨어지지 않으면 3을 빼주고, 3 카운트를 +1
3. 1과 2를 반복. 음수가 되면 3과 5로 나누어 떨어지지 않는 경우이므로 결과는 -1
또 같이 이야기를 나눠보는 도중에 제리의 도움으로 이 문제를 `수학적으로 접근`할 수 있다는 사실도 알게 되었는데요. 이미 가지고 계신 수학적 지식으로 공식을 도출해낼 수 있었다고 합니다... 일정한 규칙이 반복되나 봅니다.
같은 문제인데도 수학, 그리디, DP로 풀 수 있다는 것이 신기하고 실제로 루시드님이 DP로 접근하셔서 스터디를 통해 다양한 풀이 방식을 볼 수 있어서 좋네요ㅎㅎ 스스로 풀지는 못했지만 세 가지 풀이 방법을 조사해간 후 스터디 시간에 설명하면서 저의 지혜로 한번 흡수해보겠습니다!
---
추가로 다음 출제자가 난이도 조절을 하는데 참고할 수 있도록, 이번 문제가 쉬웠는지 안쉬웠는지 이슈에 이모지로 피드백 부탁드립니다. 
- 👍  : 난이도를 더 올려주세요
- 👎  : 난이도를 더 낮춰주세요
- 적당한 난이도였으면 이모지 X
출제자는 그냥 참고만 하시고, 그냥 본인이 내고 싶은 문제 편하게 맘대로 출제하셔도 됩니다ㅋㅋㅋ
=> [후] 20220213 풀이 제출

피오/20220216.java
* 계단을 세 번 연속 밟지 않으면서 계단의 수의 합이 가장 큰 경우의 수를 거쳐야 한다.
* i번째 계단을 밟을 때 가능한 경우는 i - 2번째 계단을 밟고 오거나, i -3번과 i - 1번 계단을 밟고 오는 경우가 있다.
* dp테이블에는 누적값이 들어있으므로 `dp[i - 3] + 계단값[i]` 과 `dp[i - 2]`의 값을 비교하여 더 큰 값을 구한후 `계단값[i]`를 더한다.
* 후, 제리, 준의 지혜
=> [피오] 20220216 계단오르기 풀이제출

후/20220218.java
1. n을 k진수로 변환(문자열 이용)
- 나머지를 더할때마다 연산이 이루어지고, 마지막에 reverse를 해주어야 하니까 StringBuilder를 사용
- 문자열로 반환("0"으로 split해줘야 하니까!)
2. k진수로 변환한 n을 "0"으로 split 해주고 요소마다 소수 여부 판별하여 소수면 카운팅
- 00이 붙어있는 경우 예외처리
- 런타임 에러 발생
- 변환한 k진수 부분이 int 범위가 벗어나는 경우가 발생할 수 있다는 것을 처음에 캐치를 못하였고 런타임 에러가 발생하고 나서야 알게 되었습니다.
- 타임아웃 발생
- 소수 판별시에 2부터 n-1까지 완전 탐색을 하면서 소수판별을 하였는데, 시간 초과가 났습니다.
- 그 다음으로 떠올린 개선안은 약수를 구할 때처럼 n / 2를 해서 구하는 것이였는데 스스로 정한 알고리즘 풀이 상한 시간(1시간)이 지나버려서 바로 제리에게 도움을 받아버렸습니다ㅎㅎ
- 제리에게 에라토스테네스의 체라는 알고리즘을 듣게 되었고, 또 n / 2 가 아니라 루트n 까지만 탐색해도 소수를 판별할 수 있다는 것을 알게 되었습니다.
[에라토스테네스의체](https://ko.wikipedia.org/wiki/%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98_%EC%B2%B4)
에라스토스테네스의 체가 소수를 구하는 경우에 가장 최적의 알고리즘이라고 하는 것 같은데, 지금 저희가 풀고 있는 문제는 n까지의 소수 전체를 구하는 것이 아닌 n이 소수인가 여부를 판별하는 것이기 때문에 반복문을 돌리다가 나누어 …
=> [후] 20220218 풀이 제출

후/20220222.java
1. 처음에는 단순하게 `N-1에 색칠된 색을 제외한 비용들 중 최소값과 그 색을 캐싱`하려고 했습니다.
- ex) 이전 집이 빨간색이라면, 빨간색을 제외한 초록색과 파란색을 비교해서 더 적은 비용을 누적하고 그 색을 저장
- dp[N] = dp[N-1] + 이 전 건물을 색칠한 값을 제외한 비용 중 최솟값, color[N] = 이번 건물을 색칠한 색
2. 그런데 이런 방법으로 하려니까, 이 전 건물에서 최소 비용을 선택하여 색칠한 색이 전체의 최선의 경우가 아니라는 것을 알게 되었습니다.
```text
1 2 3
100 200 300
```
- 이처럼 그 전 건물에서 최소값을 선택(빨간색: 1)을 하는 것이 전체의 최선의 경우가 아닐 수 있습니다.
3. `매번 N번 인덱스 값을 계산할때마다 앞의 선택을 갱신해줘야하는건가...?` 하면서 멘붕에 빠져버린 것 같아요..
4. 고민고민을 하다가 깨달음을 얻어버렸습니다... `N번째 건물에 빨간색, 초록색, 파란색을 최소 비용으로 색칠하는 모든 비용 누적하면서 캐시`해버리자고.... 
- N번째 건물에 빨간색, 초록색, 파란색을 색칠하는 세 가지 경우를 모두 캐시해야 하므로 이차원 배열을 이용하였습니다.
- 이 전까지 이미 최소 비용을 메모해 두었기 때문에, N번째 건물에서 어떤 색을 색칠하는데 드는 최소 비용은 N-1번째 건물에서 어떤 색을 제외한 두 색 중의 최소 비용 + N번째 건물의 어떤 색을 색칠하는데 드는 비용입니다. 
- 그리고 이 구한 비용을 다시 메모합니다.
5. 최종적으로 N개의 건물을 색칠하는데 드는 최소 비용은 N번째 건물까지 색칠하는데 드는 …
=> [후] 20220222 풀이 제출

포키/20220214.java
제가 생각해낸 접근방법은
1. n을  5로 나눈 나머지가 0이면 바로 출력
2. 나머지가 3 이하이거나 4면 n을 5로 나눈 몫-1 로 변경해서 다시 계산
3. 이외의 경우 3으로 나눠서 계산.
계속 통과가 안되서 고민하다가 결국 구글에 검색해서 풀었습니다.
늦게 제출해서 죄송합니다!!
[ 블로그 링크 ](https://yongku.tistory.com/entry/%EB%B0%B1%EC%A4%80-2839%EB%B2%88-%EC%84%A4%ED%83%95%EB%B0%B0%EB%8B%AC-%EC%9E%90%EB%B0%94Java)
=> [포키] 20220214 풀이 제출

포키/20220214.java, 포키/20220215.java
도저히 방법을 모르겠어서 익조와 루시드에게 설명을 들은 뒤 다시 그림을 그려보니 점화식을 발견할 수 있었습니다..
(동기...왜 저에게 이런 시련을...🤯)
ik to the jo
=> [포키] 20220215 풀이 제출

동기/20220211.java
- 설탕을 최소 횟수로 옮기고 싶어하기 때문에 5로 나누어 떨어지게 해준다.
- 입력 값이 5로 나누어 떨어질 때까지 입력 값에 3을 빼주고 result 변수에 1씩 더해준다.
- 5로 나누어 떨어지는 시점에 몫을 result에 더하고 출력한다.
- 5로 나누어 떨어지지 않고 입력 받은 수가 음수가 되면 -1을 출력한다.
- while을 무한 반복하게 하고 출력하는 시점에 프로그램을 종료 시키기 위해 따로 메서드로 만들고 출력한 뒤엔 return 시켜 해당 메서드를 종료하게 한다.
=> [동기] 20220211 풀이 제출

동기/20220216.java
제가 제출한 문제였지만 풀어보니 저는 dp 에 매우 약한 것 같습니다 ㅎㅎ.. 그래서 풀이를 찾아보고 코드를 먼저 보고 이해하려고 했습니다.
https://st-lab.tistory.com/132
https://girawhale.tistory.com/3
- dp 가 아직은 낯설어서 코드를 보고 이해하려고 했습니다. 😅
=> [donggi] 20220216 풀이 제출

동기/20220218.java
- 진법 변환을 하고 소수를 찾는 방식으로 접근했습니다.
- 변환한 숫자를 0을 기준으로 split 합니다.
- 반복문을 돌면서 숫자의 소수를 체크합니다. 
- split할 때 변환한 숫자 중 000이  있으면 "" 으로 분리되기 때문에 ""을 무시할 수 있도록 처리합니다.
- 체크한 소수 개수를 반환합니다.
- 제리와 후의 도움 ㅎㅎ..
=> [동기] 20220218 풀이 제출

동기/20220304.java
문제를 읽고 이해하지 못하여 블로그에서 접근 방법과 코드를 어떤 식으로 짜야하는지 보고 이해하려고 했습니다. i -> k 경로가 있으면서 k -> j 로 가는 경로가 있다면 i -> j 로 가는 경로는 있다라고 판단하였습니다. 이러한 알고리즘이 플로이드 와샬 알고리즘이라고 하는데 스터디 때 했던 내용이지만 이 알고리즘이 어떤건지 아직 바로 떠오르지 않았습니다 ㅜㅜ
https://steady-coding.tistory.com/94 <br>
https://girawhale.tistory.com/29
- 알고리즘 어렵네요.... 흐!
=> [동기] 20220304 경로 찾기 풀이 제출

동기/20220309.java
- 이분 탐색을 하기 위해 입력 받은 숫자카드를 정렬합니다.
- `M`개의 숫자들은 이분탐색의 `target`이 됩니다.
- 이분탐색 알고리즘을 실행하고 `숫자 카드`와 `target`이 일치하면 true, 일치하지 않으면 false를 반환합니다.
- 반환된 결과에 따라 예제와 같이 출력하기 위해 `1` 혹은 `0`을 `StringBuilder`에 담아서 출력합니다.
O(logN)
- [바킹독 이분탐색](https://www.youtube.com/watch?v=3TkaOKHxHnI)
=> [동기] 20220309 숫자 카드 풀이 제출

후/20220301.java
방법을 스스로 떠올리진 못했고요.. 무식하게 모든 경우의 수를 다 계산해봐야겠다는 생각은 했는데 뭔가 규칙같은걸 뽑아낼 수 있나 싶어서 노가다도 해봤는데ㅋㅋㅋㅠㅠ 저 모든 경우의 수를 어떻게 만들어야할지 도무지 모르겠어서 인터넷찬스 썼습니다. 풀이를 보고도 이해가 안가서 블로그 글만 한 다섯개 본 것 같아요ㅠㅠ 그 중에 제일 잘 설명되어있고 이해하는데 도움이 되었던 블로그 하나 첨부합니다.
이진 트리(더하는 경우, 빼는 경우)로 모든 경우의 수를 만들어낼 수 있다는 것을 떠올리는게 관건인 것 같습니다. 그걸 이해하고 나니깐 코드는 스스로 작성할 수 있었어요.
https://velog.io/@euneun/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%ED%83%80%EA%B2%9F%EB%84%98%EB%B2%84C-BFSDFS
=> [후] 20220301 "프로그래머스 타겟 넘버" 풀이 제출

후/20220304.java
최단 경로와 그래프 이론 부분 열심히 공부했다고 생각했는데 완전 새롭네요...
코테는 반복적으로 풀어보는게 답인 것 같아요ㅠㅠ 기억이 안나서 이코테 책 다익스트라, 플로이드 워셜 다시 학습하고 기존에 작성해둔 같은 유형의 코드를 참고하였습니다.
이코테 최단 경로
=> [후] 20220304 "백준 - 경로 찾기" 풀이 제출

동기/20220312.java
- bfs에 대해 강의를 보며 먼저 학습했습니다.
- 강의의 수도코드를 참고하며 bfs를 구현해보았습니다.
- 나이트가 방문하지 않은 좌표를 방문해가며 목표 지점까지 이동하게 했습니다.
- 방문한 좌표는 boolean 다차원 배열을 이용해 구분해주었습니다.
- queue에 node를 push 메서드로 앞에다 넣어주다가 이상한 값이 나와서 엄청 헤맸습니다..
O(NM)
[바킹독 bfs 강의](https://www.youtube.com/watch?v=ftOmGdm95XI)
https://codingtalk.tistory.com/199
=> [동기] 20220312 나이트의 이동 풀이 제출

포키/20220316.java
일반적으로는 해당 위치의 옆만 체크를 하는것과 다르게 이번 문제는 8곳이나 확인해야해서 확인할 좌표를 2개의 배열에 담아두고 for문을 통해 확인하도록 했습니다.
bfs는 많이 풀어보는수밖에 없는것 같네요..ㅎ
.....
=> [포키] - 20220316 나이트의 이동 풀이 제출

포키/20220316(2).java, 포키/20220316.java
- 하루에 하나씩밖에 못산다.
- 하루에 팔 수 있는건 제한이 없다. -> 젤 비쌀때 전부 파는게 최고.
- 최고가 이전까지는 무조건 산다.
1. point 변수에 현재 최고가를 저장한다.
2. 현재 최고가보다 큰값이 나오기 전까지는 result 변수에 `현재 최고가 - 매입가` 를 더한다.
3. 현재 최고가보다 큰값이 나오면 point 변수를 갱신한다.
2중 for문을 사용했으니 O(n^2)?
=> [포키] - 20220316 주식 풀이

동기/20220322.java
- 2중 포문으로 맨 앞 번호부터 하나씩 순회하도록 접근했다가 처참한 실패를 맛보았습니다.
- 프로그래머스 질문하기에서 sort를 사용하는 힌트를 얻었습니다.
- 문자열 배열을 sort하여 현재 `index`와 `index + 1`을 비교하였더니 하나의 테스트케이스를 제외하고 맞길래 패스한 줄 알았습니다.
- 숫자 문자열 배열의 정렬 기준을 잘못 알고있었고 접두어의 의미를 잘못 알고 있었습니다.
- 숫자 문자열 배열의 정렬 기준은 숫자의 크기 순이 아닌 숫자의 순서 순이었습니다. ("23", "1234" 를 `sort` 하면 "1234", "23" 순으로 정렬되었습니다)
- 단순히 `contains` 메서드로 `index` 숫자 문자열이 `index + 1` 안에 포함되어 있으면 된다고 생각했지만 접두어는 단어의 앞에만 붙어야했습니다. ("35"는 "235"의 접두어가 아니었고 "2", "23", "235" 가 "235"의 접두어)
- 접두어를 추출하기 위해 `String`의 `startsWith` 메서드를 이용하여 해결할 수 있었습니다.
최악의 경우 for 문을 끝까지 돈다 생각하여 O(N)..?
프로그래머스 질문하기 페이지
=> [donggi] - "프로그래머스 - 전화번호 목록" 풀이제출

후/20220420_1.java
1. 평범한 이분 탐색으로 풀이 -> 시간 초과
2. 파라메트릭 서치로 재도전 -> 틀렸습니다!
3. int -> long으로 일괄 변경
O(n log(n))...? (정렬)
막상 풀고 나서 풀이 코드를 비교해보니 평범한 이분탐색이랑 파라메트릭 서치랑 다른게 없어 보이는데.. 대체 뭔차이일까요? 알쏭달쏭하네요
=> [후] 20220420 "백준 - 나무자르기" 풀이 제출

후/20220420_2.java
동전을 가장 적게 사용해야 하므로 가능한 가치가 큰 동전부터 사용해야함!
동전 종류를 가치가 큰 동전부터(역순) 전체 순회하며 만들려는 금액에 필요한 동전 수를 더해준다. 순회 중에 가치가 동일해지면 바로 반복문 탈출
O(N)
=> [후] 20220420 "백준 - 동전 0" 풀이 제출

후/20220426_2.java
이 또한 무식하게 풀어보았습니다^-^V 그리고 통과하지 못했습니다 우하하
문자열의 압축 단위는 1~문자열의 길이/2까지입니다!
모든 압축 단위로 압축을 하여 압축된 결과 중 최소 길이를 구하여 출력하였습니다!
처음엔 48점이였는데, 질문하기 게시판을 뒤져서 `반복 횟수가 10 이상인 경우도 고려해야한다`는 사실을 찾았습니다.
기존에는 압축된 결과 문자열에서 replace를 이용하여 1을 다 없애주고 있었거든요... 
반례를 못 찾은 분들께 추천드려요ㅎㅎ 48점에서 66점이 되었습니다.
질문게시판 다뒤져서 테스트케이스 다 추가해봤는데 다 통과하는데 왜 문제는 통과를 못하는지 모르겠네요...ㅎㅎ 도와주세요 선생님들~!
(특별히 익조 선생님께 리뷰 리퀘스트를 날려봅니다...)
---
익조 선생님이 찾아주신 반례로 solve! 예외처리를 잘못하고 있었습니다ㅎㅎ
=> [후] 20220426 "프로그래머스 - 문자열 압축" 풀이 제출

포키/20220416.java
완전 비슷한 형태의 문제를 푼 기억이 있어서 이코테를 찾다가 파라메트릭 서치를 발견했고 이후에 떡볶이 문제가 있는것을 보고 참고해서 풀었습니다.
동작 과정
1. 시작점과 끝점을 정한다.
2. 중간점을 절단기 길이로 설정한다.
3. 절단기보다 긴 나무들을 차례대로 자른다.
4. 자른 나무들의 길이의 합이 가져가야 하는것보다 작다면 톱날의 길이를 줄여야하기 때문에 끝점 - 1을 한다.
5. 자른 나무들의 길이의 합이 가져가야 하는것보다 크다면 톱날의 길이를 저장하고 늘리기 위해 시작점 + 1을 한다.
6. 시작점이 끝점보다 커지기 전까지 반복한다.
- 이코테 - 7장 이진탐색
- 떡볶이 문제
=> [포키] 20220416 백준 - 나무 자르기 제출

포키/20220420.java
1. k를 동전 목록의 뒤에서부터 순회한다. -> 가장 큰 값부터 돌아야 최소 동전 개수를 구할 수 있어서.
2. 동전이 k보다 작을 경우 result에 k를 동전으로 나눈 몫을 저장한다. / k보다 동전 값이 크면 넘어간다.
3. result를 반환한다.
O(n)
=> [포키] 20220420 백준 - 동전 0 제출

포키/20220427.java
=> [포키] - 20220427 - 문자열 압축 풀이 제출

제리/20220506.java
명령어에 맞춰 단순하게 한국어로 바꾸었습니다.
userId와 닉네임을 map에 저장해서 유저의 닉네임이 변경되어도 변경된 닉네임이 출력되도록 했습니다.
userId를 순서에 맞추어 List형태로 들고있다가 map에서 닉네임을 꺼내는 식으로 구현했습니다 :)
=> [제리] 20220506 "프로그래머스 - 오픈채팅방" 풀이 제출

후/20220507.java
- `HashMap<String, String> userMap` : 사용자의 `uid`와 `nickname`을 저장하는 공간
- `ArrayList<Log> logs` : 사용자의 enter과 leave를 기록하는 공간
- 명령어가 `enter`일 때, userMap에 uid와 nickname을 put(동일한 uid를 가진 사용자가 이미 있어도 nickname으로 갱신)하고 logs에 추가
- 명령어가 `leave`일 때, logs에 추가
- 명령어가 `change`일 때, userMap에 uid와 nickname을 put(동일한 uid를 가진 사용자가 이미 있어도 nickname으로 갱신)
- Log 클래스를 정답 문자열로 변환할 수 있도록 `toString`을 오버라이딩하여 구현하였습니다.
O(N)
=> [후] 20220507 "프로그래머스 - 오픈채팅방" 풀이 제출

제리/20220511.java
각각의 노드에서 X까지 가는 데 필요한 최소 시간을 구하기 위해서는 다익스트라로는 해결이 불가능하다고 생각을 했어서 플로이드와샬로 풀었습니다.
문제를 푼 후에 여러 블로그들을 참고해보니 경로를 역전시키는 방법으로 다익스트라로 해결이 가능한 것을 보고 나중에 다시 한 번 풀어보려고 합니다 :)
O(N^3)
=> [제리] 20220513 "백준 - 파티" 풀이 제출

제리/20220515.java
각각의 S L R 이 할당된 행과 열에서 출발하는 4가지 선분 (상, 하, 좌, 우)를 기준으로 지나간 적이 있는지, 없는지를 확인하여 지나간 적이 있는 선분이 나오기 전까지 count를 증가시켜 배열에 넣은 후 모든 선분을 지나갈 때까지 반복했습니다.
=> [제리] 20220515 "프로그래머스 - 빛의 경로 사이클" 풀이 제출

후/20220518_1.java
하나의 특정한 시작 노드가 아닌, 모든 노드의 모든 최단 경로를 구해야하므로 플로이드와샬을 이용하였습니다.
O(N^3)
분명 최단경로 하나하나 다 그려보면서 열심히 공부했다고 생각했는데 오랜만에 보니 또 초면이네요..ㅎㅎ
덕분에 다익스트라와 플로이드와샬 복습했습니다ㅎㅎ 👍
=> [후] 20220518 "백준 - 파티" 풀이 제출

후/20220518_2.java
- 노드마다 모든 방향(상, 하, 좌, 우)의 방문 여부를 체크하기 위한 배열 `boolean[rowCount][colCount][4]`을 선언
- 이동하면서 길이를 증가시켜주고, 방문했던 경로에 도착하면 사이클이 발생한다고 판단, 반복문을 탈출합니다.
O(NM)? O((NM)^2)? <- 은 절대 풀릴거같지가 않은데,,, beam()도 계산을 해야하지 않을까요? 모르겠읍니다.. 
제리의 브레인
=> [후] 20220518 "프로그래머스 - 빛의 경로 사이클" 풀이 제출

제리/20220519.java
백트래킹으로 lock을 걸고 풀면서 전체탐색을 하도록 했습니다.
초기 값이 A, AA, 와 같은 경우를 처리할 수 없어서 따로 로직을 위에다가 빼서 코드가 조금 더럽네요 ㅠ_ㅠ
=> 🔀 [제리] 20220519 "백준 - 알파벳" 풀이 제출

제리/20220523.java
- 물의 높이가 0부터 max높이까지 다 탐색해서 일정한 물의 높이에서 도출된 output(섬의 개수)의 max 값을 출력하고자 했습니다.
- 일정한 물의 높이에서 output(섬의 개수)를 구하는 로직은 findCountOfIsland() 메소드에서 dfs() 함수가 호출되는 횟수를 카운트해서 섬의 개수를 도출해냈습니다.
=> 🔀 [제리] 20220523 "백준 - 안전 영역" 풀이 제출

20220601_1.java
큐 2개를 이용, 다리의 빈칸에 0을 add하여 풀이하였습니다!(코드 주석 참고)
O(N)? bridge_length * truck_weights의 길이...?일까나요...?
=> [후] 20220601 "프로그래머스 - 다리를 지나는 트럭" 풀이 제출

제리/20220526.java
다리의 길이의 위치에 해당하는 트럭을 가지고 있는 Queue (`onBridgeTruck`)와
트럭의 줄에 대한 정보를 가지고 있는 Queue (`truckLine`) 두개를 사용했습니다.
다리의 길이만큼 Queue `onBridgeTruck` 에 0을 넣고 1초마다 한칸씩 이동하도록 했습니다.
다리위에 올라가 있는 트럭의 무게를 `onBridgeWeight` 에 저장을 하고 다리 위에 올라가 있는 무게와 다음 차례의 트럭 무게를 비교해가며 Queue에서 자료를 뺴거나, 빼지 않도록 했습니다.
=> 🔀 [제리] 20220526 "프로그래머스 - 다리를 지나는 트럭" 풀이 제출

제리/20220530.java
이전에 풀었던 문제이네요 😅
처음에는 Set을 활용하지 않고 `List<String> store`에 모두 넣어서 `store.contains()`으로 듣보잡의 인원을 구했는데 시간초과가 나서 Set으로 변경한 후에 add()메서드의 반환 값 (새로운 값이 저장되면 true, 이미 존재하는 값이라서 새로운 값이 저장되지 않는다면 false)를 이용해 듣보잡의 인원을 구하도록 변경했던 기억이 나네요.
=> 🔀 [제리] 20220530 "백준 - 듣보잡" 풀이 제출

동기/20220529.java
- 트럭 큐, 브릿지 큐 총 두 개의 큐를 만들어 다리가 감당할 수 있는 무게를 업데이트해주면서 브릿지 큐에 트럭 큐에서 가져온 트럭을 넣어 다리를 건너게 하였습니다.
ㅎㅎㅎ..!
=> [동기] 20220529 "프로그래머스 - 다리를 지나는 트럭" 풀이 제출

동기/20220601.java
- 듣도 못한 사람의 수를 받아 Set에 저장하고
- 보도 못한 사람을 입력 받아 Set에 저장된 데이터를 `contains` 로 비교하여 리스트에 저장
- sort하고 출력
=> [동기] 20220601 "백준 - 듣보잡" 풀이 제출

동기/20220525.java
- 방문하지 않은 알파벳이면 dfs 실행
- 너무 오래 붙잡고 있어서.. 올려놓고 계속 도전하겠읍니다..
=> [동기] 20220525 "백준 - 알파벳" 풀이중

포키/20220531.java
- 트럭이 다리에 올라간 시점의 초를 담는 time 큐
- 이미 지나간 트럭을 담는 passed 큐
- 다리 위에 있는 트럭들을 담는 passing 큐 
1. 트럭이 모두 지나기 전까지 while 문을 돌린다.
2. 다리 위에 트럭이 있을 경우, time 큐의 첫번째 값과 다리를 지나는데 걸리는 시간을 더해서 현재 시간과 일치하면 
3. passing에서 트럭을 빼서 passed에 넣는다. 
- 이때 다리 위의 트럭들의 무게합에서 지나간 트럭의 무게를 뺀다.
4. 만약 다리 위의 무게 + 건너지 않은 트럭의 무게가 다리가 지탱할 수 있는 무게를 넘지 않을 경우 해당 트럭을 passing에 추가하고, 다리위의 트럭들의 무게합에 추가한다.
=> [포키] 20220601 "프로그래머스 - 다리를 지나는 트럭" 풀이 제출

포키/20220601.java
처음에는 리스트에 n명의 사람을 저장한 뒤, m번 for문을 돌면서 contains 함수로 듣보잡을 걸러내려고 했으나 시간초과가 떴음
<이후 풀이 과정>
1. List에 모든 입력값을 저장한 뒤 sort 함수를 통해 정렬한다.
2. List를 순회하며 현재 값과 다음값이 일치하면 정답을 저장하는 List에 추가한다.
=> [포키] 20220601 "백준 - 듣보잡" 풀이 제출 

후/20220608_2.java
빡대가리라 근가 점화식 뽑아내는것이 힘들었읍니다,,, 두뇌 풀가동!
O(N)
=> [후] 20220608 "백준 - 구간 합 구하기" 풀이 제출

후/20220615_1.java
- 문제에 제시된 탈락 조건들을 boolean 조건식으로 작성하였습니다.
1. 앞사람이 말한 단어의 마지막 문자로 시작하는 단어를 말해야 합니다. - `isInvalidWord`
2. 이전에 등장했던 단어는 사용할 수 없습니다. - `isDuplicatedWord`
-  중복 검사는 `HashSet`을 사용하여 수행하였습니다.
3. 한 글자인 단어는 인정되지 않습니다. - `isInValidLength` 
- 전체 단어들을 순차적으로 순회하며, 탈락 조건에 걸리면 탈락자의 번호와 차례를 리턴해주었습니다.
- 번호와 차례는 수학 연산을 통하여 구하였습니다! 계산이 약해서 몇 번 틀렸는데 제리가 도와주었어요ㅎㅎ 감사합니다! 
O(N)
=> [후] 20220615 "프로그래머스 - 영어 끝말잇기" 풀이 제출

제리/20220603.java
별도의 클래스 없이 int[]로 풀다가 포기했습니다.. 머리아프네요
코드에 todo 주석으로 적은 것처럼 논리 흐름대로 코드를 작성해서 풀었습니다. :)
```
Frame 이 모두 차 있지 않고
만약 Frame에 있으면 리스트에 있는 값에 추천 수를 1 더함
없으면 그냥 리스트에 넣음
Frame 이 모두 다 차 있고
만약 Frame에 있으면 리스트에 있는 값에 추천 수를 1 더함
없으면 리스트를 정렬한 후에 첫번째 인덱스를 제거하고 리스트에 넣음
```
=> 🔀 [제리] 20220519 "백준 - 후보 추천하기" 풀이 제출

동기/20220615.java
- 의식의 흐름대로 로직을 작성해보았습니다. 중복 체크를 하기 위해 Set을 사용했습니당
=> [동기] - 20220615 프로그래머스 "영어 끝말잇기" 제출

제리/20220609.java
저번에 썻던 Set에 add 반환값 (값이 새로 들어가면 true, 이미 있는 값이면 false)와 이전단어, 현재 단어의 마지막글자, 첫 글자 비교를 해서 게임이 종료되는 조건에 flag를 세워서 풀었습니다.
종료되었을 때 사람의 인원과 종료된 시점의 진행횟수를 통해 단순한 수학 계산을 통해 정답을 도출했습니다.
=> 🔀 [제리] 20220609 "프로그래머스 - 영어 끝말잇기" 풀이 제출

제리/20220615.java
백트래킹으로 모든 경로를 찾은 후 제일 짧은 경로를 찾는 로직으로 풀었다가 시간초과가 나서 bfs로 접근했습니다.
`visited[][]` flag를 통해서 방문하지 않고 `map` 이 1인 곳을 찾으며 bfs 탐색을 통해 n, m 위치까지 가는 path 길이를 찾았습니다.
=> 🔀 [제리] 20220615 "백준 - 미로 탐색" 풀이 제출

후/20220625_1.java
dfs를 이용하여 1번 컴퓨터부터 탐색을 시작하여, 네트워크에 연결된 컴퓨터 수를 카운트해주었습니다!
O(N)
이 문제는 dfs로 풀든 bfs로 풀든 상관이 없는 문제라고 판단되는데 보통 어떤 기준으로 알고리즘을 선택하시는지 궁금합니다!
-> (자문자답) 시간복잡도때문에 오랜만에 동빈북을 펴봤는데, 일반적인 경우 보통 DFS 보다는 BFS 구현이 조금 더 빠르게 동작한다고 하네요! 무지성으로 DFS으로 풀었는데, 두 알고리즘으로 모두 풀이 가능한 경우라면 BFS를 선택하는게 더 좋겠어요ㅎㅎ
=> 🔀 [후] 20220625 "백준 - 바이러스" 풀이 제출

제리/20220617.java
백트래킹을 통해서 course의 수에 따라서 모든 메뉴의 경우의 수를 찾은 이후에 Map의 key값으로 메뉴, value로는 메뉴가 주문된 횟수를 저장했습니다. 또 저장할 때 course에 따라서 최대 주문된 횟수를 저장하는 Map을 별도로 하나 더 두어서 course 별로 최대주문 횟수를 찾아서 List에 저장하여 답을 구했습니다.
=> 🔀 [제리] 20220617 "프로그래머스 - 메뉴 리뉴얼" 풀이 제출

제리/20220620.java
1. 던전의 순서를 조합한다. ex) 1 2 3 4, 1 3 2 4, 1 4 2 3 ...
2. 조합된 순서를 int[]에 담는다.
3. 조합된 모든 경우의 수를 List<int[]>에 담는다.
4. 조합된 모든 던전 입장 순서에 따라서 던전을 돌며 최대 입장가능한 던전의 수를 센다.
- 최대 입장 가능한 던전의 수가 만약 던전의 개수와 같다면 break 를 통해 더이상 던전을 진행하지 않는다.
- 어차피 이미 다 돌 수 있는 경우의 수를 찾았기 때문!!
=>  🔀 [제리] 20220620 "프로그래머스 - 피로도" 풀이 제출

후/20220625_2.java
1. 입력받은 문자열을 공백(" ")으로 split
2. 공통된 변수형(split[0])을 따로 정의
3. split된 배열을 공통된 변수형의 다음 요소부터 순회하며,
a. 요소를 reverse시킴
b. 두번째 인덱스부터(첫번째는 , 또는 ; 이므로) 순회하며 문자가 배열 또는 변수명인지 검사
- 변수명 - 'a' ~ 'Z' -> 현재 인덱스부터 substring하여 다시 reverse한 후 추가
- 배열 - ']' (문자열을 뒤집어두어서 ']'로 시작) -> "[]"를 추가해주고 인덱스 한번 더 증가시켜줌
ㅎㅎ..?!
=> 🔀 [후] 20220625 "백준 - iSharp" 풀이 제출

동기/20220712.java
- 문제 접근도 못해서 블로그에 나온 풀이를 보고 이해하려 했습니다
https://youngest-programming.tistory.com/586
- dfs 탈출 조건에 단체 사진을 찍을 인원이 총 8명이기에 `names` 가 8이 됐을 때 조건문이 실행되는 건 이해하겠으나 7로 해줘도 답이 나오는 이유는 뭘까요?.?
- `check` 메서드 중 
- `names.indexOf(d.charAt(0))` 
- 만들어진 사진 대열에서 `N~F=0` 에서 `N` 의 위치를 찾는거였습니다! 질문을 적으면서 이해했네요
- `index + 1` 은 1을 더해주지 않으면 비교하는 조건식이 제대로 작동하지 않는데 왜그런지 이해가 되지 않습니다 🙄
=> [동기] 20220712 프로그래머스 단체사진찍기 풀이 제출

포키/20220628.java
",", ";" 다 지우고 2중 for문 돌면서 해결했습니다.
변수명이 한글자가 아닌 경우도 있다는걸 몰라서 헤맸네요;;
=>  [포키] - 20220628 백준 아이샵 풀이 제출 

동기/20220523.java
- 브루트포스 + dfs
- 각 높이에서 dfs로 잠기지 않는 지역이 몇 개나 나오는지 찾고 그 중 가장 큰 값을 출력
ㅎㅎ!
- 제리와 구글 블로그 ㅎ_ㅎ
=> [동기] 20220523 "백준 - 안전 영역" 풀이 제출

아더/20220711.java
모든 경우의 수를 구한 뒤 한 줄마다 조건을 체크해서 조건을 통과하면 카운트를 세는 방법으로 접근했습니다.
`O((N!) / (N-M)!)`   => 8! => 40,320
Hoo's brain!
=> [아더] 20220711 프로그래머스 단체사진찍기 문제 풀이 추가

익조/20220213.java
3개의 if 분기문을 이용하여 풀이했습니다.
첫번째 분기문은 설탕이 5 이상일 경우, 두번째 분기문은 설탕이 3인 경우, 세번째 문기문은 설탕이 4인 경우입니다.
설탕이 3인 경우는 결과값이 1이고, 설탕이 4인 경우는  결과값이 -1이므로 단순합니다.
하지만 설탕이 5 이상인 경우에는 그리디 알고리즘을 적용하여 풀 수 있었는데, (5로 나누어 떨어지는 경우는 단순)
문제에서 요구하는 최소의 봉지 개수를 충족시키기 위해 설탕을 5로 먼저 나누고 0으로 떨어지지 않으면 5를 하나씩 빼서 그 자리를 3으로 메우고자 했습니다.
최종적으로 N이 3으로 떨어지면 5와 3의 몫 값 합계를 출력시키도록 했고, 떨어지지 않는다면 -1을 출력시키도록 했습니다.
=> [익조] 20220213 "백준 설탕배달" 풀이 제출

익조/20220215.java
> + 다이나믹 프로그래밍 방법을 이용했습니다.
> 
> + 우선 n = 1 ~ 4 까지의 규칙성을 찾으려고 노력했습니다.
> 
> + 규칙성을 유추해본 결과 n = 1, n = 2일 때는 단 하나의 경우의 수만 존재했습니다.
> 
> + n = 3일 때는 2가지의 경우의 수가 존재했는데 `첫번째 계단 + 마지막 계단`인 경우 또는 `두번째 계단 + 마지막 계단`에 해당하는 경우입니다.
>   + 마지막 계단은 반드시 도착한다는 전제 사항 중요
> 
> + n = 4일 때 역시 2가지의 경우의 수가 존재했는데 `첫번째 계단 + 세번째 계단 + 마지막 계단`인 경우 또는 `첫번째 계단 + 두번째 계단 + 마지막 계단`에 해당하는 경우입니다.
> 
> + n = 4인 경우부터 메모라이즈된 값을 불러오도록 할 수 있었습니다.
>   + 우선 `첫번째 계단 + 세번째 계단 + 마지막 계단`인 경우 첫번째 계단까지의 메모라이즈된 값을 불러온 후 세번째 계단값과 마지막 계단값은 별도로 더해주는 식을 세울 수 있었습니다. 이는 계단을 연이어 3계단을 오를 수 없기 때문입니다.
> 
>   + 또한 `첫번째 계단 + 두번째 계단 + 마지막 계단`인 경우 두번째 계단까지의 메모라이즈된 값을 불러온 후 마지막 계단값만 별도로 더해주는 식을 세울 수 있었습니다.
> 
> + 최종적으로 이 두 개의 값 중 더 큰 값이 문제에서 요구하는 계단값의 합 최대값이므로 이를 토대로 점화식을 세워 알고리즘을 구할 수 있었습니다.
> 
> ### 사진(규칙성 찾는 과정)
> > …
=> [익조] 20220215 "백준 계단오르기" 풀이 제출

동기/20220618.java
-  풀이법을 떠올리지 못해 블로그를 통해 풀이를 이해하였습니다 ㅡㅜ
https://infodon.tistory.com/63
=> [동기] 20220718 백준 - 스타트와 링크 풀이 제출

동기/20220410.java
- AEIOU 를 5진수로 생각하여 풀어보려다가 구현하지 못하여 오늘도 풀이를 찾아 보게 되었습니다 😢
- 풀이의 힌트를 통해 예제의 I = 1563 이 A = 1, E = 752 즉 각각의 알파벳이 781 이라는 차이를 갖게 된다는 걸 알게 되었습니다.
- `word` 를  charAt() 메서드를 통해 문자를 하나씩 비교하여 계산되게 하였습니다.
- 2중 for 문 중 바깥쪽 for 문은 word.length() 만큼 반복하고, 안쪽 for 문은 5까지 반복하게 하여 O(... 
- [풀이를본곳](https://dev-jwblog.tistory.com/74)
- 코드를 보고 이해하다 20번째 줄 코드 `diff = (diff - 1) / 5` 에서 1 을 빼주지 않아도 정답이 나오는데 왤까요 😵‍💫
=> [동기] 20220410 프로그래머스 - 모음 사전 풀이 제출

동기/20220416.java
**시간 초과 풀이**
- 나무의 개수를 입력 받을 때 `Math.max()` 메서드를 이용하여 가장 큰 값 max 를 저장
- while(true) 무한 반복하면서 max 보다 나무의 값이 크면 `나무 - max`
- for 문이 끝났을 때 M 과 같은 결과가 나오지 않으면 `max - 1` 하여 다시 for 문 실행
**이분 탐색을 이용한 풀이**
```java
for (int i = 0; i < n; i++) {
if (heights[i] - mid > 0) {
sum += (heights[i] - mid);
}
}
if (sum < m) {
max = mid;
} else {
min = mid + 1;
}
```
- 음.........
=> [동기] 20220416 백준 - 나무 자르기 제출

동기/20220420.java
- 최소값을 찾기 위해 동전의 값이 큰 것부터 접근하여 K원을 만드는 데 필요한 동전 개수를 파악하려고 했습니다.
- 큰 값부터 접근하다가 K원보다 작을 때 해당 값을 K원에서 빼주고 count 를 증가시킵니다.
- K원이 0이 되면 해당 count를 출력하고 프로그램을 종료 시킵니다.
- 풀어보니 다른 분들께 너무 쉬웠진 않았을까 하는 생각이 듭니다..
=> [동기] 20220420 "백준 - 동전 0" 풀이 제출

동기/20220427.java
- 입력 받은 문자열을 1 부터 압축 가능한 길이까지 반복하여 각각의 압축된 길이 중 가장 작은 길이를 반환하면 되겠다고 생각하였습니다.
- 소중한 5천원을 지켜보고자 여러 블로그의 풀이를 참고하였지만 도저히 이해가 되지 않아 미완의 상태로 제출하게 됐습니다 ㅜ.ㅜ
=> [동기] 20220427 프로그래머스 - 문자열 압축 풀이 제출

동기/20220502.java
- String 에서 숫자를 가져올 때 Character 로 하나씩 가져와서 Character.isDigit() 으로 true 일 때 숫자를 가져오는 방법으로 접근했습니다.
- 가져온 숫자를 key 로 하여 Map 에 저장하고 value 를 기준으로 내림차순하여 출력하려고 했습니다 (구현하지 못했음 ㅜㅜ)
- 후우
=> [동기] - 20220502 프로그래머스 튜플 풀이 제출

후/20220719_1.java
백트래킹을 이용하여 팀의 조합을 구하고, 해당 조합마다 능력치의 차이를 계산하여 최솟값을 갱신하였습니다.
처음에 백트래킹을 잘못 짜서, 타임아웃이 났는데 명품 네비게이터 @ak2j38의 길잡이로 조합을 구하였습니다.
...?!
아더의 두뇌
=> 🔀 [후] 20220719 "백준 - 스타트와 링크" 풀이 제출

후/20220719_2.java
스택을 이용하여 전위순회결과로 트리를 구해보고자 했으나 실패하고, 아더에게 수도 코드 힌트를 받아
새로운 노드를 추가하거나 후위 순회할 때 재귀를 이용하였습니다.
O(n)...............
아더의 수도코드 힌또
```
if 현재노드의 값보다 들어온 값이 작으면){
if (leftchild가 널이면) {
left에 새로운 노드 생성해서 넣는다
} else {
insert 재귀호출
}
}
```
=> 🔀 [후] 20220719 "백준 - 이진 검색 트리" 풀이 제출

20220719_2.java
전위 순회된 값을 root 노드에 삽입한 후 후위순위시에는 마지막 노드를 찾을 때까지 탐색 메서드를 재귀호출 하였습니다.
https://minhamina.tistory.com/83
https://girawhale.tistory.com/59
=> [피오] 20220719 백준 - 이진 검색 트리 풀이 제출

20220719.java
백트래킹과 이중 for문을 이용한 조합 풀이. 확실히 공부했습니다..!
https://st-lab.tistory.com/122
=> [피오] 20220719 "백준 - 스타트와 링크" 풀이 제출

피오/20220712.java
엉뚱한 방법으로 문제를 풀다가 뒤늦게 깨닫고 답지를 봤습니다 🥲 dp 오랜만에 보네요.
=> [피오] 20220712 백준 - 스티커 풀이 제출

후/20220711.java
1. 대기실에서 응시자(P)만을 추출하여 별도의 리스트에 추가 - `extractPerson`
2. 응시자들의 맨해튼 거리가 2이하인 경우에만 자리 사이가 파티션으로 막혀있는지 검사 - `isSafe`
- 응시자 간의 맨해튼 거리가 2이하인 경우는 다음과 같은 6가지 경우 밖에 없으므로, 이 중에 자리 사이가 파티션으로 막혀있어 거리두기가 잘 지켜지고 있는 경우만 따로 `true`를 리턴하도록 처리해주었습니다.
- 여기서 삽질을 좀 했던게,, 문제를 잘못 이해해서 파티션이 좌우로만 막혀있는줄 알고 그림처럼 가로로 PXP는 안전하지만 세로로 PXP는 거리두기를 지키고 있지 않다고 생각했습니다;;;;;
3. 거리두기를 지키고 있지 않은 케이스가 하나라도 있다면 바로 0을 리턴, 해당 대기실에 대한 검사는 종료
4. 다음 대기실을 1~3을 반복하여 검사
O(대기실 수*대기실 크기(25)*대기실 크기(25))...?!
=> 🔀 [후] 20220711 "프로그래머스 - 거리두기 확인하기" 풀이 제출

제리/20220710.java
총 인원 수가 8명으로 모든 경우의 수 (8! = 40320) 를 만든 이후에 조건에 맞는 경우를 count하면 될 것 같아서 모든 경우의 수를 구한 후 (`List<String sequences`) 조건을 체크했습니다.
조건을 체크 할 때 어떻게 해야 할 지 모르겠어서 구글링을 해서 답을 참고했습니다,, 😅
=> 🔀 [제리] 20220710 "프로그래머스 - 단체사진 찍기

제리/20220701.java
=> 🔀 [제리] 20220701 "백준 - 스티커" 풀이 제출

포키/20220716.java
백트래킹이라고 생각하고 접근했지만 풀리지가 않아서 결국 블로그를 보고 풀었습니다..😭
=> [포키] 20220719 백준 스타트와 링크 풀이 제출

포키/20220719.java
이진 트리를 먼저 만든 뒤, 왼쪽 -> 오른쪽 -> 루트 순서대로 출력했습니다
=> [포키] 20220719 백준 이진 검색 트리 풀이

포키/20220627.java
=> [포키] - 20220628 백준 바이러스 풀이 제출

포키/20220609.js
=> [포키] - 20220609 프로그래머스 "영어 끝말잇기" 제출

포키/20220510.java
문제의 예시를 보고 회의 종료 시간을 정렬하면 되겠다는 힌트를 얻었습니다.
1. 시작시간, 종료시간을 가진 배열에 값을 담고 List에 저장한다.
2. 끝나는 시간을 기준으로 List를 정렬한다.
3. 반복문을 돌면서 현재 끝나는 시간과 다음 회의 시작 시간을 비교해서 겹치지 않으면  count를 늘린다.
한번에 풀리지가 않아서 제리교수님의 도움을 받아 문제를 해결했습니다.
시작 시간을 정렬하지 않으면 
```
(4,4)
(3,4)
```
위와 같은 상황이 발생할 수 있다는걸 알았네요ㅎ
정렬이 맘대로 안되서 Time클래스를 추가적으로 생성했습니다.
=> [포키] - 20220506 백준 - 회의실 배정 풀이 제출

포키/20220518.java
=> [포키] 20220518 프로그래머스 - 빛의 경로 사이클 풀이 제출

포키/20220524.java
=> [포키] 20220525 "백준 - 안전 영역" 풀이 제출

익조/20220217.java
우선 이 문제를 풀기 위해서는 주어진 양의 정수 n을 k진수로 변환시켜주었어야 했습니다. 이때 k는 `3~10으로 최대 10진수이므로 필요한 수는 0~9에 해당하므로` 이를 활용하기 위해 String 변수 base에 "0123456789"를 저장시켜주도록 했고 while문을 통해 k 진수의 수를 구했습니다.(k진수 구할 때 reverse 뒤집기 유념)
문제에서 요구하는 조건들을 살펴보면 결국 주어진 k진수에서 "0을 구분으로 존재하는" 수 중 소수의 개수를 구하는 것입니다. 이를 위해 split를 통해 "0"으로 구분시켜 각각의 수들을 얻어냈고 각각의 수별로 소수인지 판별하도록 했습니다.
해당 수가 소수인지 판별할 때 일반적인 for문이나 while문을 통해서 구하면 시간복잡도 성능이 안좋아집니다. 저는 시간복잡도 성능을 개선하기 위해서 해당 수의 인자(약수)를 구한 후 이를 HashSet에 저장시키도록 했고(중복 방지) 소수의 조건인 1과 자기 자신의 수로만 떨어지는지 체크함으로써 해당 수가 소수인지를 판별했습니다.
최종적으로 소수로 판별될 때마다 result 값에 1씩 더해주어 결과값을 구할 수 있었습니다.
소수 판별 로직은 제가 CS05 함수형 프로그래밍에서 사용했던 로직을 사용했습니다.
HashSet의 자료형을 Integer나 Long으로 지네릭이 지정된 경우 collect의 두번째 인자에서 원인불명의 빨간줄이 표기되서 지네릭을 지정하지 않았습니다. 이 오류 원인은 아직 잘 모르겠습니다..
=> [익조] 20220217 "프로그래머스 k진수에서 소수 개수 구하기" 풀이 제출

제리/20220717-02.java
풀었던 문제이고 최근에 풀고 있던 유형이네요 😄
Node Class를 선언하고 루트노드를 기준으로 새로운 데이터를 넣는 메서드를 만들어 트리 구조를 만들어서 문제를 풀었습니다.
더 복잡한 문제는 Node Class와 Tree Class를 모두 선언해서 풀기도 하는 데 현재 문제에서는 Tree class는 필요 없을 것 같아서 생략했습니다.
=> 🔀 [제리] 20220717 "백준 - 이진 검색 트리" 풀이 제출

제리/20220717-01.java
사람들의 조합을 구한 이후에 (ex 1, 2, 3, 4 // 5, 6, 7, 8) 능력치를 구하기 위해서 (1,2 / 1, 3, / 1, 4 / 2, 3/ 2, 4/ 3, 4) 조합을 한 번 더 구하여 능력치를 구했습니다.
함수를 재사용할 수 있을 줄 알고 설계를 하다가 코드가 이상해졌어요.. ㅠㅅㅠ
dfs() 함수가 능력치를 구하기 위한 `combi` 를 만드는 함수이고
dfs2() 함수가 사람들의 조합을 구하는 함수입니다.
<br>
푼 이후에 `boolean[] visited` 를 활용하는 것이 훨씬 효율적인 것을 인지하였습니다. 다음부터 이런 문제는 visited 유무로 팀을 구분하도록 해야겠습니다!
=> 🔀 [제리] 20220710 "백준 - 스타트와 링크" 풀이 제출

아더/20220712.java
1. 사람들의 위치를 큐에 저장합니다.
2. 큐가 빌 때까지 상하좌우, 상하좌우2칸, 대각선의 위치에 다른 사람이 있는지 확인합니다.
아마 `사람수 X 3 X 4` 정도 일 것 같은데..... 정확히 모르겠습니다 ㅠㅠㅠ
=> [아더] 20220712 거리두기 확인하기 문제 풀이 추가

20220601.java
=> [루시드] 20220601 "프로그래머스 - 다리를 지나는 트럭" 풀이 제출

루시드/20220503.java
- 괄호 등을 모두 제거하고, 순수 숫자만 List에 담습니다.
- List의 Size를 기준으로 정렬을 진행하고,
- 맨 앞 리스트부터 훑어보며 숫자가 없는 경우에만 answer List에 add합니다.
=> [루시드] 20220503 프로그래머스 튜플 풀이 제출

익조/RGB 거리.java
문제에서 요구하는 것은 N개의 집이 주어질 때 한 집당 R G B 중 한 가지 색으로 색칠을 할 때에 최소한의 비용입니다. 이때 중요한 점은 현재 색칠하는 집의 색과 이전 집에 색칠된 색과 동일해서는 안된다는 점입니다.
이를 위해 저는 한 집에 색칠할 수 있는 색(R, G, B) 중 가장 적은 비용의 색을 선택하도록 했고 이 색을 다음 집에 R G B 색칠 비용에 누적 합산시켜주도록 했는데, 중복되면 안되므로 해당 색은 제외시켜 합산시켜주었습니다.
이때 getMinValueAndIndex 메서드에서는 R G B 중 최소 비용값과 해당 인덱스(0~2)를 정수형 배열로 반환시켜주도록 했습니다. 여기서 최소 비용값은 다음 집 R, G, B 색칠 비용에 누적시키기 위함이며, 해당 인덱스 값은 색의 중복 방지를 하기 위함이었습니다.
최종적으로 마지막 집에서의 R, G, B 색칠 비용은 처음 집부터 누적하여 합산해준 결과이므로 이 중에서의 최소값은 전체 집을 최소 비용으로 칠할 수 있는 경우에 해당합니다.
<br/>
앞서 구한 풀이의 경우 최소 비용과 인덱스를 이용하는 등 논리적으로 다소 번잡한 느낌이 있어 좀 더 유연하게 수정하고자 했습니다.
우선 현재 집에 색칠 비용값들에 이전 색칠 비용의 최소값을 누적 합산해주는 논리는 같지만 이번에는 중복 방지를 위해 인덱스를 사용하지 않고 현재 집에 대한 R 색칠 비용에 이전 집에 대한 G와 B 색칠 비용 중 최소값을 합산해주었고, 현재 집에 대한 G 색칠 비용에 이전 집에 대한 R와 B 색칠 비용 중 최소값을 합산하는 방식 등으로 구현했습니다. 
최종적으로 마지막 집에 대한 …
=> [익조] 20220222 "백준 RGB 거리" 풀이 제출

익조/20220225.java
while 반복문을 통해 주어진 **문자열 s의 첫 부분부터 순차적으로 다음 문자와의 포함 관계(반복 사용 유무)를 체크**하도록 하였습니다. 이때 반복문이 1사이클 돌 때마다 s의 길이는 1씩 감소합니다.(첫 번째 문자순으로 삭제)
또한 temp 문자열 변수를 만들었는데 이 temp 문자열 변수에 반복이 없는 문자열을 저장하도록 하고 while 반복문이 끝날 때까지(주어진 문자열 s의 길이가 0이 될 때까지) result 변수에 최대값 비교(삼항연산자)를 통해 지속적으로 할당해주었습니다. 이 result 값은 문제에서 요구하는 "반복되는 문자가 없는 단어의 최대 길이" 값입니다.
만일 temp 문자열과 다음 문자 간 포함 관계에 있지 않다면 반복되지 않는 것으로 생각할 수 있으므로 이를 temp 변수에 추가시켜주었습니다.
하지만 다음 문자와 포함관계에 있다면 2가지 경우로 나누어 볼 수 있었는데, 우선 temp 변수 끝 문자와 해당 문자가 같다면 temp 변수에는  **temp 변수 문자열의 끝 문자(= 다음 문자)만** 할당하도록 했습니다. 이는 temp 변수 문자열의 끝 문자를 그대로 놔두면 다음 문자 단어와 중복되기 때문입니다.
반대로 temp 변수 끝 문자와 해당 문자가 같지 않다면 temp 변수에는 temp 문자열에서 해당 문자(다음 문자)가 발견된 지점부터 temp 문자열 끝까지(temp.substring(temp.indexOf(nextChar) + 1) 그리고 해당 문자를 더하여 할당하였습니다.
최종적으로 반복문을 모두 돌고 나면 주어진 문자열 s의 길이는 0이 되며(모든 경우의 수 확인 …
=> [익조] 20220225 "리트코드 Longest Substring Without Repeating Characters" 풀이 제출

아더/20220713.java
1. 처음엔 `가치/무게`로 전부 변환한 뒤 이를 정렬해 높은 값들을 배낭에 넣는 형식으로 문제에 접근했으나 따로 알고리즘이 있었어요....ㅠㅠ
2. `0-1 배낭 알고리즘`을 사용해 풀이했습니다.
3. `DP`배열을 K 크기만큼 선언한 뒤 이를 뒤에서부터 채우며 최댓값으로 갱신하는 풀이 방식입니다.
`DP`를 이용한 풀이이므로 `O(KN)` 입니다.
[0-1 배낭 문제 알고리즘](https://sskl660.tistory.com/88)
=> [아더] 20220713 BOJ_12865_평범한배낭 문제 풀이 추가

동기/20220726.java
- 최단 거리를 구하기 위해 다익스트라 알고리즘을 이용해야했던 문제였습니다.
- 블로그 보고서야 최단 거리는 다익스트라를 이용해야 한다는 걸 알았습니다..
향상된 다익스트라라서 O(ElogV)..?
https://velog.io/@lifeisbeautiful/Java-%EB%B0%B1%EC%A4%80-1916%EB%B2%88-%EC%B5%9C%EC%86%8C%EB%B9%84%EC%9A%A9-%EA%B5%AC%ED%95%98%EA%B8%B0-with-%EC%9E%90%EB%B0%94
어렵다!
=> [동기] - 20220726 백준 최소비용 풀이중

아더/20220715.java
1. N명의 사람 중 N/2명의 사람을 뽑아 각 팀의 배정해야 합니다.
2. 각 팀원들을 뽑을 땐 `중복없이 순서없이` 즉 `조합`으로 팀원을 뽑아야 합니다.
3. `selected` 배열은 스타트팀으로 뽑은 사람의 경우, `isSTeam`배열은 스타트팀으로 뽑은 사람들의 인덱스를 `true`로 표현합니다.
4. `(N / 2) + 1`만큼 팀원을 뽑으면 현재 각 팀의 능력치의 차이를 최소값에 갱신합니다.
=> [아더] 20220715 BOJ_14889_스타트와링크 문제풀이 추가

후/20220723.java
우선순위 큐를 이용하여 다익스트라 알고리즘을 구현하여 풀었습니다.
1. 최단 거리 테이블을 초기화
2. 방문하지 않은 마을 중에서 최단 거리가 가장 짧은 마을을 선택(이 때 우선순위 큐를 이용하면 O(N)이 아닌 O(logN)으로 최단 거리가 가장 짧은 마을 구하기 가능)
3. 해당 마을을 거쳐 다른 마을로 가는 비용을 계산하여 최단거리 테이블 갱신
4. 최단거리 테이블을 더이상 갱신할 수 없을 때까지 2~3 반복
O(버스수 log 마을수)
동빈북(분명 열심히 공부했는데 왜 오랜만에 풀면 또 새로울까요)
=> 🔀 [후] 20220723 "백준 - 최소비용 구하기" 풀이 제출

후/20220726.java
확률이 뭔소린지 전혀 모르겠어서, 제리선생님, 익조선생님의 풀이도 보고 블로그도 보고 다 찾아보았습니다ㅎㅎ. 선생님들은 map도 동적으로 메모리를 아주 최적화하셨던데 저는 멍청이라 그냥 문제 조건에서 커버 가능한 30으로 초기화해주었습니다ㅎ_ㅎ
O(n^n)? 맞습니까?
제리선생님, 익조선생님의 휘알 
앤도 https://steady-coding.tistory.com/80
=> 🔀 [후] 20220726 "백준 - 미친 로봇" 풀이 제출

제리/20220726-02.java
다익스트라 어렵네요.. 혼자서 풀다가 도저히 못풀겠어서 블로그를 참고해서 풀었습니다.
=> [제리] 20220726 "백준 - 최소비용 구하기" 풀이 제출

동기/20220326.java
- 처음 접근할 땐 땅 높이의 최저와 최고를 갖게하고 최저 높이와 최고 높이의 개수를 통해 평탄화 할 높이를 결정하게 하였습니다.
- 그렇게 평탄화 할 높이가 결정되면 인벤토리에 필요한 블럭의 개수가 평탄화하기에 충분한지 확인하였습니다.
- 예제 세 문제는 어찌 통과하길래 제출해보았더니 1퍼센트에서 광탈.
- 결국 이번에도 구글링을 하여 풀이를 보았습니다.
- 평탄화할 땅의 최저 높이와 최고 높이만큼 반복하게 하고 땅의 좌표를 하나씩 반복합니다.
- 현재 땅의 높이 (최저와 최고 높이의 사이에 있는) 와 해당 좌표의 땅의 높이를 뺀 값을 파악합니다.
- 그 값이 0보다 크면 해당 좌표는 블럭을 제거하여 땅을 평탄화해야한다는 판단을 할 수 있습니다.
- 뺀 값만큼 블럭을 제거하고 제거하는 시간을 2초이기에 뺀 값 * 2 를 시간 값을 저장하는 변수에 더해줍니다.
- 뺀 값이 0보다 작다면 블럭을 채워 땅을 평탄화 해야한다는 판단을 할 수 있습니다.
- 마이너스가 된 차이값을 절대값으로 다루어서 블럭을 채우는 시간은 1초이기에 절대값 자체를 시간 변수에 더해줍니다.
- 좌표를 전부 확인하면 인벤토리에 있는 블럭의 개수와 더해진 시간 값을 갖게 됩니다.
- 블럭의 개수가 마이너스가 됐다면 해당 높이로 평탄화 할 수 없기에 `continue` 를 해주어 다음 높이에서 위의 작업을 반복할 수 있도록 합니다.
- 블럭의 개수가 마이너스가 되지 않았다면 `answerSecond` 값보다 좌표를 확인하며 생긴 시간 변수가 더 작다면 최소값이기 때문에 `answerSecond` 변수에 시간 변수 값을 저장해주고 …
=> [donggi] 20220326 백준 - 마인크래프트 풀이 제출

루시드/20220518.java
- 다익스트라를 여러 번 돌리고 X노드에 대해 X -> Y -> X를 구해 제일 큰 값으로 갱신했습니다.
- 생각해보니 플로이드 워셜이 정석 같네요 ; ㅎㅎ
=> [루시드] 20220518 백준 - 파티

아더/20220718.java
1. 처음엔 데이터의 갯수가 주어지지 않아 어떻게 입력받아야하나 고민을 많이했습니다;;;;
2. 1번은 intellij에서 테스트하는 방법에 대한 고민이었습니다. 제가 해결한 방법은 `BufferedReader`를 사용했을 때 입력값을 입력하고 `command + d`를 눌러 `EOF`를 명시적으로 입력해주는 방법으로 IDE에서 테스트를 했습니다.
3. 다음엔 전위순회로 주어진 결과의 맨 처음 값이 루트노드라는 생각을 하지 못해서 많이 헤맸습니다. 
4. 입력값을 `insert`메소드로 이진검색트리로 만들어줍니다.
5. 변환한 이진검색트리를 `postOrder`메소드를  통해 후위순회해서 결과를 출력합니다.
[Java Tree 구현](https://dev-whoan.xyz/40)
=> [아더] 20220718 BOJ_5639_이진검색트리 문제 풀이 추가

후/20220801.java
DP를 이용하여 매번 최소, 최대값을 갱신하였습니다.
O(N)
=> 🔀 [후] 20220801 "백준 - 내려가기" 풀이 제출

동기/20220802.java
=> [동기] - 20220802 백준 내려가기 풀이 제출

20220726_2.java
블로그를 참고하여 dfs + 백트래킹으로 풀었습니다. 
보드의 중앙에서 시작하여 이동 확률이 존재하는 곳으로만 방문하면서 확률을 계산해나갔습니다.
https://youngest-programming.tistory.com/596
=> [피오] 20220726 "백준 - 미친 로봇" 풀이 제출

후/20220705.java
이 문제도 스스로 풀어보려고 노력했으나,,, 답을 찾아봤네요ㅠ_ㅠ
찾아보니까, `1) 순열을 이용해서 야무지게 구하는 방법`과 `2) 모든 조합을 구한 후에 조건에 부합하는지 검사하는 방법` 이렇게 두 가지 방법이 있는 것 같습니다,,,만 나무위키랑 유튜브 보면서 순열ㅎㅎ공부를 해봤지만 저는 뼈문과인가봐요 모르겠습니다,,, 이거 왜 하고 있는지도 모르겠어서 모든 조합을 구한 후에 조건에 부합하는지 검사하는 방법으로 풀어보았습니다!
...?! O(N^N)...?(N=8)이려나요...?
https://onejunu.tistory.com/92
https://jisunshine.tistory.com/145
=> 🔀 [후] 20220705 "프로그래머스 - 단체사진 찍기" 풀이 제출

후/20220704.java
처음엔 또트래킹을 떠올렸다가,,, 입력 조건을 보고 DP로 풀어야겠다는 생각은 했습니다,,,만,,,
그림도 그려보면서 많은 시간을 태웠지만 도저히 점화식이 보이지 않았습니다 8ㅅ8
결국 답을 보고 말았네요,,,
O(TN)
https://fbtmdwhd33.tistory.com/76
=> 🔀 [후] 20220704 "백준 - 스티커" 풀이 제출

아더/20220723.java
1. 전형적인 우선순위 큐를 활용한 다익스트라로 풀이했습니다.
우선순위 큐를 사용했으므로 `O(ElogV)` 입니다.
=> 🔀 [아더] 20220723 BOJ_1916_최소비용구하기 문제 풀이 제출

루시드/20220802_2.java
- 하나 씩 점을 계산해서 result에 넣고, 마지막에 result에 해당하는 위치를 *로 대체했습니다.
- max, min 범위랑, -좌표를 어떻게 표현해야할 지 한참 헤맸습니다; ㅠㅠ
https://sangsangss.tistory.com/195
=> [루시드] 20220802 "프로그래머스 - 교점에 별 만들기" 풀이 제출

제리/20220801.java
문제 조건에 맞춰서 교점이 정수인 경우에만 List에 담은 후 최대, 최소값을 구해서 resize를 했습니다.
resize된 값을 기반으로 별을 찍는 로직을 구성한 후에 answer에 담았습니다.
메모리 초과가 계속 나서 고생했네요.
long maxX, maxY, minX, minY 의 값이 최대/ 최소값을 보장하지 못한 변수로 선언이 되어 있어서 answer의 배열이 너무 커져 메모리 초과가 발생했던 것 같습니다. Long.MAX_VALUE, Long.MIN_VALUE로 해결했습니다.
=> 🔀 [제리] 20220801 "프로그래머스 - 교점에 별 만들기" 풀이 제출

제리/20220731.java
전형적인 dp문제로 max, min을 선언한 후 최대값과 최소값을 구했습니다.
=> 🔀 [제리] 20220731 "백준 - 내려가기" 풀이 제출

피오/20220621_2.java
정렬을 하면 되는 건가 싶어서 정렬 로직을 생각해보다가, 단순히 정렬만으로 푸는 문제는 아닌 것 같다는 
생각이 들었습니다. 아마 한 시간 정도 삽질하다 답지 보게 될 것 같습니다.
https://cano721.tistory.com/104
=> [피오] 20220621 프로그래머스 - 피로도 풀이 제출

아더/20220726.java
확률을 어떻게 처리해야할지 몰라 답지를 봤습니다....... 역시 수학은 넘나 어렵네요
확률 쪽을 다시 공부하고 이해해봐야겠어요
[미친로봇 풀이](https://steady-coding.tistory.com/80)
=> 🔀 [아더] 20220726 BOJ_1405_미친로봇 풀이 제출

루시드/20220301.java
N이 20 제한이므로, (+, -)에 대한 순열인 2^20 => 1,000,000ns < 1s이기 때문에 완전 탐색으로 풀 수 있다고 생각되었습니다.
따라서 입력된 수와 동일한 길이의 operator 배열을 순열로 만들고, 재귀 탈출 조건인 L==N에서 연산후 target과 일치할 경우에 count를 올렸습니다.
배열이 아닌 ArrayList를 사용했다가 애를 먹었습니다; 배열을 사용해서 이전 값을 덮어씌우는 방식으로 접근해야 했습니다.
=> [루시드] 20220301 "프로그래머스 타겟 넘버" 풀이 제출

후/20220621_1.java
백트래킹을 이용하여 풀이하였습니다.
O(N^N) (N:던전의 개수)
=> [후] 20220621 "프로그래머스 - 피로도" 풀이 제출

익조/20220228.java
해당 문제는 DFS를 통해 해결 했습니다. solution 메서드에서 숫자가 담긴 배열 numbers와 타겟 넘버 target을 파라미터로 받으면 이를 해당 클래스의 멤버 변수로 선언해주었습니다. 이는 dfs 메서드를 통해 재귀 함수를 반복적으로 호출 시 이 값들을 지속적으로 참조하기 위함이었습니다. 
문제를 푸는 매커니즘은 배열로 **주어진 숫자들이 각각 음과 양으로 이루어질 수 있는 모든 경우의 수를 탐색**하여 각각의 경우의 수에서 타겟 넘버와 일치하는지 확인하는 것이었습니다.
이를 위해 dfs 메서드에서는 두개의 dfs 메서드를 재귀 호출하게 되는데, 하나는 현재 index 값의 배열 값을 더해주면서 재귀하도록, 다른 하나는 현재 index 값의 배열 값을 빼주면서 재귀하도록 했습니다.
이때 현재 index 값의 배열 값을 계속 더해주는 루트(route)로 재귀한다면 주어진 모든 수를 더하는 경우의 수가 생길 것이고, 현재 index 값의 배열 값을 계속 빼주는 루트(route)로 재귀한다면 주어진 모든 수를 빼는 경우의 수가 생길 것입니다.
실제로는 현재 index 값의 배열 값을 더해주거나 빼주었다가 또 다시 다음 index 값의 배열 값을 더해주거나 빼주었다가 하면서 모든 경우의 수를 탐색하게 됩니다.
문제 풀 때 위에 DFS/BFS 유형을 보고 DFS 방식으로 풀어서 실전이었으면 애 먹었을 것 같습니다... 😂
=> [익조] 20220228 "프로그래머스 타겟 넘버" 풀이 제출

익조/20220303.java
여기에다가 접근 방법을 쓰다 보닌까 본의 아니게 스포가 되는 것 같아서(슬랙 노출) **접근 방법은 개인적으로 제 기술 블로그에 풀이 회고 형식으로 작성**해보았습니다. 내용은 다음 링크를 통해 확인하실 수 있습니다.
https://ikjo.tistory.com/150
=> [익조] 20220303 "백준 - 경로 찾기" 풀이 제출

익조/20220308.java
https://ikjo.tistory.com/158
입력 for 반복문 : N회
크기 N의 정수형 배열 요소에 정수 할당 : 3회
3 * N = 3N회
입력 for 반복문 : M회
크기 M의 정수형 배열 요소에 정수 할당 : 3회
3 * M = 3M회
탐색 for 반복문 : N회
if문 : 1회
크기 M의 정수형 배열 특정 인덱스 요소에 정수 할당 : 2회 (있을 수도 있고 없을 수도 있음)
(1 + 2) * N = 3N회
출력 for 반복문 : M회
출력 연산 : 2회
2 * M = 2M회
최종 빅오 시간복잡도 6N + 5M = 11N = O(n)
음... 아래 링크를 참고하여 시간복잡도를 계산해보기는 했는데 이렇게 하는게 맞는지는 잘 모르겠어요...🤣
시간복잡도 작성 참고 자료 : https://yoongrammer.tistory.com/79
=> [익조] 20220308 "백준 - 숫자 카드" 풀이 제출

아더/20220731.java
전형적인 `DP`로 해결하는 유형으로 점화식을 잘 생성한다면 쉽게 풀 수 있는 문제입니다.
물론 저는 점화식 90퍼센트 만들어놓고 마지막을 잘 못써서 시간을 한참 낭비했습니다....
아이디어는 `DP`라는 배열에 하나씩 채워가는데 해당 칸에 올 수 있는 방법 중 최댓값/최솟값의 경우를 나누어 풀이했습니다. 
지금보니 공간복잡도가 허락한다면 최댓값배열, 최솟값배열을 두 개 만들어 반복문 한 번으로 처리할 수 있을 것 같네요.
`DP`로 풀이했기 때문에 `O(N)`입니다.
=> 🔀 [아더] 20220731 BOJ_2096_내려가기 문제풀이 추가

20220809_1.py
=> [루시드] 20220809 프로그래머스 - 게임맵최단거리 문제 풀이 제출

20220316.java
접근 방법 1 : 2중 for문 -> 시간 초과
접근 방법 2 : 개선된 2중 for문 -> 시간 초과(91%에서)
접근 방법 3 : 1중 for문(핵심 : 뒤에서부터 탐색 ) -> 성공    ※ 백준 게시판에서 힌트 발견
내용 정리 : https://ikjo.tistory.com/167
O(N^2) --개선--> O(N)
백준 게시판
=> [익조] 20220316 "백준 - 주식" 풀이 제출

루시드/20220802.py
최대, 최소를 별도로 갱신하는 DP로 접근하였습니다.
O(N)
=> [루시드] 20220802 백준 - 내려가기 풀이 제출

동기/20220809_1.java
=> [동기] 20220809 백준 - 부분합 풀이 제출

동기/20220809.java
=> [동기] 20220809 프로그래머스 - 게임맵최단거리 문제 풀이 제출

제리/20220806-01.java
start point와 end point를 두어서 투 포인터로 문제를 해결했습니다.
기준값 (s) 보다 큰 경우 앞 포인트를 이동하여 sum을 감소시켰고 기준값 보다 작은 경우 뒤 포인트를 이동하여 sum을 증가시키며 정답을 구했습니다.
=> 🔀 [제리] 20220806 "백준 - 부분합" 풀이 제출

제리/20220806-02.java
전형적인 그래프 탐색 문제로 bfs로 접근했습니다. maps에 값을 이전의 값에서 + 1 씩 하여 출발점에서 maps까지 도착하는 데 필요한 최소 거리를 저장하며 그래프 탐색했으며 한 번 방문한 곳은 visited 배열을 통해서 다시 방문하지 않도록 했습니다.
만약 목적지에 방문하지 않았다면 출발지에서 목적지까지 연결되지 않았다는 의미이기에 - 1을 반환하였고 목적지에 방문했다면 연결되어 있다는 의미이기에 maps에 들어 있는 데이터를 출력하도록 했습니다.
while()문 안에서 목적지에 도달한다면 바로 break;를 통해 빠져나오는 로직을 만들면 조금 더 효율적인 로직을 구성할 수 있을 것 같습니다.
=> 🔀 [제리] 20220806 "프로그래머스 - 게임 맵 최단거리" 풀이 제출

익조/20220318.java
문제를 잘못(?) 이해하여 꽤 오랜 삽질을 했습니다..😂
그래도 풀긴 했는데, 그닥 좋은 시간복잡도 성능을 갖는 것 같진 않습니다. 🤣
좀 더 개선해볼 수도 있겠지만 일단 이 문제는 이 정도에서 마무리 하고자 합니다 ㅎㅎ
참고 자료 : https://ikjo.tistory.com/170
O(N^2)      ※ 1 <= N <= 1000
=> [익조] 20220318 "프로그래머스 - H-Index" 풀이 제출

익조/20220321.java
사실 이 문제 3월 7일에 풀었었던 문제였는데 덕분에 또 보게 되어 유익했습니다 👍
이번 기회에 TreeMap 자료구조에 대해 다시 한 번 복습하는 시간을 가졌습니다. 
https://ikjo.tistory.com/156
O (N * logN * ???)
+ for 반복문 : N
+ TreeMap의 startsWith : logN
+ TreeMap의 tailMap  : ??? 이 메서드의 경우 시간 복잡도를 찾아봐도 안 나오네요 ㅠㅠ
=> [익조] 20220321 "프로그래머스 - 전화번호 목록" 풀이 제출

후/20220816_1.java
이번 문제 굉장히 딥히컬또 하다는 조언을 듣고, 문제 한번 쓱 읽어본 후 바로 답지를 보았습니다ㅎㅎ
혼자서는 절~대 풀이를 떠올리지 못했을 문제네요ㅎㅎ 빠르게 답지를 본 것이 현명한 선택이였습니다.
역시 선배들의 말은 언제나 옳군요.
O(문자열1의 길이 * 문자열2의 길이)
https://sskl660.tistory.com/90
https://www.youtube.com/watch?v=nyXkaHUahHk
=> 🔀 [후] 20220816 "백준 - LCS" 풀이 제출

동기/20220816_1.java
- 완전탐색으로 접근하였습니다
- O(N^2)
- 나단, 제리의 도움이 있었습니다
=> [동기] 20220816 백준 - 리모컨 문제 풀이 제출

동기/20220816.java
- lcs 알고리즘을 이용하였습니다
- O(N * M)
[lcs 알고리즘이란](https://velog.io/@emplam27/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-LCS-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Longest-Common-Substring%EC%99%80-Longest-Common-Subsequence
)
=> [동기] 20220816 백준 - LCS 풀이 제출

20220809.java
bfs로 풀었으며 방문할 칸에 +1 을 해주어 visited로 활용하였습니다.
=> [피오] 20220809 프로그래머스 - 게임맵최단거리 문제 풀이 제출

후/20220815.java
=> 🔀 [후] 20220815 "프로그래머스 - 게임 맵 최단거리" 풀이 제출

아더/20220808.java
BFS를 통해 각 자리에 도달할 수 있는 최소값을 갱신했습니다.
BFS만 쓰면 되는 문제라 살짝 쉬웠던 것 같네요!
=> 🔀 [아더] 20220808 프로그래머스 - 게임맵최단거리 문제 풀이 제출

20220816_2.py
나올 수 있는 수가 최대 500000이지만, 999999까지 눌러서 갈 수 있기 때문에 999999까지 경우를 계산해서 최소를 구하는 방식으로 접근했습니다.
다만 target 기준으로 +1, -1씩 증감하며 매칭되는 결과로 계산하려고 했는데 -1에서 음수로 가는 부분을 최적화하지 못해 전 범위를 그냥 계산했습니다.
=> [루시드] 20220816 백준 - 리모컨 문제 풀이 제출

루시드/20220816_1.py
LCS 알고리즘을 공부하고 풀었네요; 어렵어렵
https://velog.io/@emplam27/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-LCS-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Longest-Common-Substring%EC%99%80-Longest-Common-Subsequence
=> [루시드] 20220816 백준 - LCS 풀이 제출

아더/20220811.java
저번 스터디에서 풀었던 문제인데 접근방식이 기억나지 않았네요;;;;; 아래 링크를 보고 다시 공부했습니다.
[LCS](https://sskl660.tistory.com/90)
LCS에는 두 가지가 있습니다. 
1. `Longest Common Subsequence` : 가장 긴 부분수열을 구하는데 부분수열이 떨어져 있어도 됨!
2. `Longest Common Substring` : 가장 긴 부분수열을 구하는데 부분수열이 붙어있어야 됨!
이 문제는 떨어져있어도 되므로 1의 방식으로 접근하게 됩니다.
기본적으로 LCS는 DP에 속하기 때문에 점화식을 생성하는 것이 매우 중요합니다.
2차원 배열을 선언한 뒤 동일한 문자를 만나면 +1씩 해주며 한 칸 한 칸 채워갑니다!
`O(N^2)` 입니다.
=> 🔀 [아더] 20220811 BOJ 9251 LCS 문제 풀이 제출

피오/20220615.java
제리가 저번에 보여준 Set.add()를 이용해보았습니다. set.add()가 false를 리턴하거나 끝글자와 앞글자가 일치하지 않으면 틀린 사람을 리턴합니다.
=> [피오] 20220615 "프로그래머스 - 영어 끝말 잇기" 풀이 제출

익조/20220326.java
https://ikjo.tistory.com/179
O(N * M * (최댓값 - 최솟값 + 1))
+ N : 마인크래프트 맵의 세로 값
+ M : 마인크래프트 맵의 가로 값
+ 최댓값 : 입력받은 블록 높이 중 가장 큰 값
+ 최솟값 : 입력받은 블록 높이 중 가장 작은 값
=> [익조] 20220326 "백준 - 마인크래프트" 풀이 제출

익조/20220330.java
최초에 주어진 진실을 판별할 수 있는 사람들을 통해 주어진 파티들에서 지민이가 진실을 말 할 수 없는 파티를 체크하고 해당 파티에 포함된 사람들을 다시 진실을 판별할 수 있는 사람들로 분류하여 다시 주어진 파티들을 탐색했습니다. 이를 구현하기 위해 Set과 Queue를 이용했습니다.
https://ikjo.tistory.com/183
O(M * 50 * M) 
M : 파티의 수(1<=M<=50)
50: 각 파티에 참석할 수 있는 사람의 수
※ 정확하지 않습니다. 😥 두번째 M이 사실 M 보다는 작을 거 같은데 최악의 경우가 몇인지 정확하게 파악하기가 어렵네요.. 😂
=> [익조] 20220330 "백준 - 거짓말" 풀이 제출

피오/20220628.java
`Map<Integer, List<Integer>>` 를 이용하여 노드를 구성하였습니다. 여러 사람들 코드를 보니 배열로도 가능한 걸 덮어놓고 Map부터 생각한 것같네요.
=> [피오] 20220628 "백준 - 바이러스" 풀이 제출 

제리/20220814.java
도저히 모르겠어서 아더와 익조가 추천한 블로그를 보고 풀었습니다...
어렵네요 ㅠㅅㅠ
아더, 익조의 PR
=> 🔀 [제리] 20220814 "백준 - LCS" 풀이 제출

후/20220823_1.java
Queue를 이용하여 LRU를 구현하였습니다.
100,000 * 30 ?!
@ak2j38 의 디버깅 도움
=> 🔀 [후] 20220823 "프로그래머스 - [1차] 캐시" 풀이 제출

익조/20220402.java
해당 문제에서 요구하는 것은 주어진 수의 집합에서 6개의 수를 고를 수 있는 경우의 수입니다. 즉, 주어진 수에 대해 6개의 조합을 구하는 것인데, 자바를 통해 조합을 구하는 것에 대해 고민하던 중 아래 참고자료(기술 블로그)를 참고할 수 있었는데 많은 도움이 되었습니다! 저 같은 경우에는 평상시에 익숙한 재귀함수를 이용한 마치 DFS 탐색과 같은 방법으로 조합을 구했습니다.
https://ikjo.tistory.com/187
??? 😂
https://minhamina.tistory.com/38
=> [익조] 20220402 "백준 - 로또" 풀이 제출

익조/20220409.java
저번 로또 문제처럼 뭔가 조합을 구하는 느낌이었지만 또 다른 느낌의 문제였습니다. 우선 DFS를 이용하여 풀이할 수 있었습니다. DFS를 통하여 A, E, I, O, U 사전순으로 조합된 단어들을 탐색했는데, 이때 목표하는 단어(target)와 일치할 경우 전역변수 result에 현재 단어 번호(cnt)를 할당시켜주었습니다. 단어의 개수는 1개 이상 5개 이하이므로 단어의 개수가 만일 5를 초과하면 해당 깊이 우선 탐색의 분기를 종료시키도록 했습니다.
=> [익조] 20220409 "프로그래머스 - 모음 사전" 풀이 제출

익조/20220412.java
처음 접근 방법은 n이 1일 때부터 순차적으로 `영화의 제목에 들어간 수`를 구하여 `규칙성`을 찾아서 문제를 해결하고자 했습니다. 그리하여 다음과 같이 1~60까지 차례대로 적어보면서 나름의 규칙을 찾아보려고 했습니다.
<br/>
<br/>
여기서 `7번째 ~ 16번째까지의 수(10개의 수)`는 맨 뒤(1의 자리수)에서 1씩 증가하고 `17번째 ~25번째 수(9개의 수)`는 맨 앞에서 1씩 증가하며 이러한 규칙으로 `26~35번째 수(10개의 수)`는 다시 맨 뒤에서 1씩 증가하고 `36~44번째 수(9개의 수)`는 다시 맨 앞에서 1씩 증가하는 것을 확인할 수 있었습니다. 이러한 규칙에 따라 코드를 작성해보았는데, 문제는 나중에 어느 시점에 가면 66600이 되는데 이때부터는 기존의 규칙에 따라 증가하지 않는다는 점이었습니다. 😥 결국 규칙성을 찾는 방법을 포기하고 더이상 이 문제에 시간을 할애할 수 없어 답안지(아래 기술 블로그 참고)를 보고 말았습니다. 😇
브루트 포스를 이용한 방법으로서 최초 1번째 제목의 수 666에서 시작해 다음 666이 들어가는 수가 나올 때까지 1을 반복적으로 계속 더해줍니다. 다음 666이 나오는 수(2번째 제목의 수)는 1666으로, N번째의 제목의 수를 구할 때까지 이 같은 방식을 반복합니다.
https://st-lab.tistory.com/103
=> [익조] 20220412 "백준 - 영화감독 숌" 풀이 제출(GG - 답지 봤어요 😇)

피오/220823.java
=> [피오] 20220823 "프로그래머스 - 1차 캐시" 풀이 제출

루시드/20220822_2.py
BFS를 이용해, 각각의 경우에 D, S, L, R을 모두 집어 넣고 큐에서 꺼내어 답이 나올때까지 반복했습니다.
계속 시간초과가 나는데 익조의 풀이를 참고해서 L, R을 단축시켰습니다 ㅠㅠ
=> [루시드] 20220822 "백준 - DSLR" 풀이 제출

20220822_1.py
=> [루시드] 20220822 "프로그래머스 - 1차 캐시" 풀이 제출

동기/20220818.java
- 입력 받은 도시가 캐시에 들어있는지 아닌지 확인하며 answer 를 갱신해주었습니다
O(N)
=> [동기] 20220818 프로그래머스 - 1차 캐시 풀이 제출

아더/20220819.java
도시들의 이름배열을 순회하며 리스트에 하나씩 넣으며 리스트에 있다면 캐시에 있는 것으로 판단하고 +1, 없다면 +5를 해주었습니다.
예외처리 상 중요한 부분은 캐시사이즈가 0인 경우였는데 이 경우를 잘 예외처리해주면 어렵지 않게 해결 가능합니다!
=> 🔀 [아더] 20220819 프로그래머스 - 캐시 문제 풀이 추가

포키/20220822.java
LinkedList를 사용해서 풀었습니다.
캐시되어 있지 않을 경우가장 먼저 들어간 값을 제거하고 새로운 값을 캐시에 넣었습니다.  
만약 이미 캐시가 되어 있으면 기존 값을 제거하고 새로운 값을 넣었습니다.
캐시의 크기가 0인 경우를 생각못해서 조금 해맸습니다;
=> [포키] 20220823 프로그래머스 1차 캐시 풀이 제출

포키/20220725.java
이코테를 통해 최단 경로는 다익스트라 알고리즘 이라는걸 알게되어 도전했지만 구현에 애를 먹어서 결국 블로그를 참고했습니다. 😭
(최단 경로 = 다익스트라 or 플로이셜.. 외우겠습니다;;)
=> [포키] - 20220726 백준 최소비용 풀이 제출

포키/20220726.java
dfs + 백트래킹...
방문을 검사하는 이차원 배열 사이즈를 잘못 생각해서 헤맸습니다.
결국 다른분들의 pr을 참고해서 틀렸다는걸 알게되어서 풀 수 있었습니다.
=> [포키] - 20220726 백준 미친 로봇 풀이 제출

포키/20220801.java
처음에 무지성 dfs접근했다가 낭패를 봤습니다. (전형적인 dp문제였는데..)
dp로 재접근해서 풀었습니다.
=> [포키] - 20220802 백준 내려가기 풀이 제출

포키/20220808.java
=> [포키] - 20220809 프로그래머스 게임 맵 최단거리 풀이

포키/20220815.java
고민하다가 결국 구글에 LCS 알고리즘에 대해 검색해봐서 풀었습니다..
[링크 1](https://velog.io/@emplam27/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-LCS-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Longest-Common-Substring%EC%99%80-Longest-Common-Subsequence)
[링크 2](https://twinw.tistory.com/126)
=> [포키] 20220815 백준 LCS 풀이 제출

아더/20220830.java
제리 선생님과 익조 선생님의 탈출조건에 영감을 받아서 해결할 수 있었습니다......
다른 풀이는 다 비슷하네요!
=> 🔀 [아더] 20220828 "프로그래머스 - 두 큐 합 같게 만들기" 풀이 제출

익조/20220415.java
이분 탐색을 이용하여 풀이했습니다. 이 문제 같은 경우에는 보자마자 이취코 교재에 실려 있는 `떡볶이` 문제가 바로 떠올랐습니다. 더욱이 절단기 높이의 `최댓값`을 구하라는 조건을 보고 `파라메트릭 서치`를 바로 떠올릴 수 있었습니다. 아이디어 자체는 바로 떠오르긴 했지만 자료형의 범위를 미처 생각하지 못해 `왜맞틀`의 함정에 빠져 시간을 오래 지체하게 되었습니다. 😥
https://ikjo.tistory.com/200
```
5 2000000000
1000000000 1000000000 1000000000 1000000000 1000000000
정답 : 600000000
======
3 2
2 2 2
정답 : 1 -> 1 + 1 + 1 = 3
=========
1 5
6
정답 : 1
=====
3 2
1 1 1
정답 : 0
=======
2 2
1 2
정답 : 0
=======
5 10
5 7 16 24 9
정답 : 15 -> 1 + 9 = 10
=========
5 7
9 11 13 15 17
정답 : 12 -> 1 + 3 + 5 = 9
===========
5 7
8 10 12 14 16
정답 : 11 -> 1 + 3 + 5 = 9
=======
5 7
1 2 2 3 4
정답 : 1 -> 1 + 1 + 2 + 3 = 7
=====
1 1
1
정답 : 0
=====
3 17
15 20 34
정답 : 18
17 -> 3 + 17 = 20
18 -> 2 + 16 = 18
=======
5 18
43 20 18 45 23
정답 : 35 -> 8 + 10 = 18
=======
5 5
10 20 30 40 50 …
```
=> [익조] 20220415 "백준 - 나무 자르기" 풀이 제출

익조/20220418.java
k원을 만드는데 필요한 동전 개수 최솟값을 구하기 위해 k를 동전의 큰 수부터 나누어 구한 `몫`을 차례대로 결과값(result)에 더해주도록 했습니다. 이때 k가 0이면 더이상 나누어 떨어지지 않으므로 for문에서 break 되도록 했습니다.
https://ikjo.tistory.com/203
O(N)
=> [익조] 20220418 "백준 - 동전 0" 풀이 제출

익조/20220425.java
+ (1 단위로 압축 시) 문자열의 첫번째 문자를 가지고 두번째, 세번째 등 각각의 문자를 순서대로 비교하면서 일치하는지 여부를 검사합니다.
+ 일치하는 경우 multiple 변수(초기값 1)의 값을 1씩 증가시킵니다.
+ 일치하지 않는 경우 별도의 압축 문자열(zipString) 변수에 multiple 값(문자열 형태로)과 첫번째 문자를 추가 할당해줍니다.
+ 두번째 문자를 가지고 세번째, 네번째 등 각각의 문자를 순서대로 비교하면서 2~3번 작업을 반복합니다.
+ 모든 문자를 비교했을 경우 2 단위로 압축하여 1~4번 작업을 반복합니다.
=> [익조] 20220425 프로그래머스 - 문자열 압축 풀이 제출

루시드/20220830_1.py
- deque를 사용하였습니다. 현재 합의 크기에 따라 양쪽 배열에서 하나씩 값을 가감하여 답을 찾았습니다.
- 처음 탐색되는 배열이 두 종류이기 때문에 2번 탐색했습니다.
=> [루시드] 20220830 "프로그래머스 - 두 큐 합 같게 만들기" 풀이 제출

루시드/20220830_2.py
recursive를 통해 4번의 quad를 반복하였습니다. quadCheck를 통해 모든 값이 일치하면 0 또는 1의 count를 증가하였습니다.
=> [루시드] 20220830 "프로그래머스 - 쿼드압축 후 개수 세기" 풀이 제출

제리/20220821.java
List 를 캐시로 사용했습니다.
캐시에 존재하면 시간을 1 증가시킨 후 데이터를 꺼내어 다시 최근으로 넣어주고
캐시에 존재하지 않고 캐시가 가득 차 있으면 가장 오래된 캐시를 지우고 데이터를 넣은 후 시간을 5 증가시켰습니다.
캐시에 존재하지 않고 캐시가 가득 차 있지 않으면 캐시에 데이터를 넣은 후 시간을 5 증가시켰습니다.
remove(0) 연산과 remove(city) 연산이 있어서 LinkedList를 사용했습니다. 
만약 remove(0)을 ArrayList로 하게 된다면 1번 인덱스부터 끝까지 앞으로 하나씩 떙겨와야 해서 비효율적입니다!
=> 🔀 [제리] 20220821 "프로그래머스 - [1차] 캐시" 풀이 제출

20220823.java
도저히 못풀겠어서 답을 봐버렸습니다 ㅠㅠ
[참고 블로그](https://velog.io/@kimmjieun/%EB%B0%B1%EC%A4%80-9019%EB%B2%88-DSLR-Java-%EC%9E%90%EB%B0%94)
=> 🔀 [제리] 20220823 "백준 - DSLR" 풀이 제출

후/20220828.java
테스트 케이스 25~27 실패(90/100)
반복문 탈출 조건을 모르겠어서 익조의 블로그를 참고하여 풀이하였습니다...
만, 일부 테스트 케이스가 통과하지 못하고 있는데 이유를 모르겠어서 일단 제출해봅니다.
O(N)
https://ikjo.tistory.com/318
=> 🔀 [후] 20220828 "프로그래머스 - 두 큐 합 같게 만들기" 풀이 제출

루시드/20220809_2.py
투 포인터로 접근하였습니다. end를 for문 밖에서 고정하고 안에서 start를 가능한 곳까지 올려 결과를 갱신합니다.
=> [루시드] 20220809 백준 - 부분합 풀이 제출

후/20220904.java
다익스트라를 이용하여 풀이하였습니다.
- 최단 거리 갱신하는 부분 조건
- 연결된 노드 추가할 때 양방향으로 추가하기
두 포인트에서 실수해서 디버깅하는데 시간을 많이 보냈네요😢 
O(E log V)
과거의 다익스트라 코드(언제쯤 안보고 풀 수 있을까요... 계속 반복해야겠습니다)
=> 🔀 [후] 20220901 "프로그래머스 - 배달" 풀이 제출

후/20220905.java
~~테스트 케이스 4, 9, 10, 11 실패 (61.5/100)~~
~~예외 케이스를 모르겠어서, 선생님들의 풀이를 보고 마저 고쳐보려고 합니다!~~
~~(문제 다시 읽어보니, 다중 집합 관련된거같은데,,, 박대갈휘라서 뭔말인지 모르겠습니다 하하하하하)~~
@ak2j38 의 설명을 듣고 솔브하였습니다!
문제의 설명대로 하나하나 구현하였습니다.
1. 입력으로 들어온 문자열을 두 글자씩 끊어서 집합의 원소로 만든다. -> `List<String> set(String str)`
이 때, 영문으로 된 글자 쌍만을 List에 추가하여 영문 외의 글자가 들어 있는 경우 글자 쌍을 버림 
2. 집합 하나를 순회하면서, 다른 집합에 일치하는 글자 쌍이 있는지 검사하면서 교집합 원소의 개수를 구한다. -> `int intersectionCount(List<String> set1, List<String> set2)`
3. 교집합의 크기와 합집합의 크기를 이용하여 자카드 유사도를 구한다. -> `double jaccardSimilarity(int intersectionCount, int unionCount)`
4. 문제에서 요구하는 출력 형식으로 출력하기 위해 65536을 곱한 후에 정수부만 출력한다.
=> 🔀 [후] 20220905 "프로그래머스 - 뉴스 클러스터링" 풀이 제출

동기/20220906.java
- 문자열을 다중 집합으로 변환
- 집합의 교집합, 합집합 개수 카운팅
- 교집합이 0일 때 아닐 때, 합집합이 0일 때 아닐 때에 따른 결과 값을 반환하였습니다!
- 질문하기에서 반례를 보았읍니다
=> [동기] 20220906 프로그래머스 - 뉴스 클러스터링 풀이 제출

제리/20220827.java
배열을 큐로 변환하면서 각각의 큐의 합을 구했습니다.
이후에 큐의 합이 더 큰 곳에서 작은 곳으로 데이터를 넘기면서 두 큐의 합이 같아질 때까지 반복했습니다.
합이 같아질 수 없을 때 -1 리턴 조건의 경우 (큐의 크기 + 1) * 2 보다 많이 반복했을 때 두 큐가 같아지지 않는다면 절대로 두 큐의 합이 같아질 수 없는 것을 활용했습니다.
=> 🔀 [제리] 20220827 "프로그래머스 - 두 큐 합 같게 만들기" 풀이 제출

아더/202200904.java
우선순위 큐를 사용한 다익스트라 알고리즘을 적용해서 풀이했습니다.
풀긴했는데 지속가능한 코드로 개선해보고 싶습니다.
`O(E log V)`
=> 🔀 [아더] 20220904 "프로그래머스 배달" 풀이 제출

루시드/20220906_2.py
주어진 경로를 반복해서 확인하는 BFS로 접근하였습니다. 일반적인 플로이드워셜(3중 for문)보다 성능이 나았습니다.
=> [루시드] 20220906 프로그래머스 배달 풀이 제출

루시드/20220906_1.py
set의 intersect(교집합), union(합집합)을 이용하였습니다.
=> [루시드] 20220906 "프로그래머스 - 뉴스 클러스터링" 풀이 제출

제리/20220907.java
이미 포키의 답안을 확인한 이후에 문제를 접해서 포키의 코드를 참고해서 풀이했습니다.
포키 코드 좋네요 👍
=> 🔀 [제리] 20220907 "프로그래머스 - [1차] 뉴스 클러스터링" 풀이 제출

동기/20220913.java
- 보드를 그린다
- 보드를 네조각내기 위해 중간 지점을 찾는다
- 보드를 네조각낸다
- 네조각을 다 순회하지 않고 한조각만 순회한다.
- 순회할 한조각을 찾는다.
- r행이 중간 지점보다 크면 3, 4번째 조각에서 시작
- 작으면 1, 2번째 조각에서 시작
- c열이 중간 지점보다 크면 2, 4번째 조각에서 시작
- 작으면 1, 3번째 조각에서 시작
==============================
`제리` 풀이를 보고 풀 수 있었습니다 😌
- 사분면의 위치에 따라 `answer` 변수에 
- 입력 받은 행과 열을 `size` 변수를 기준으로 재귀 동작하게 하였습니다
- 행과 열이 `size`보다 작으면 1사분면에서 재귀를 호출합니다
- 행은 `size`보다 작고 열은 `size`보다 크다면 2사분면에서 재귀를 호출합니다
- `answer` 에 1사분면 칸만큼 더해줍니다
- 행은 `size` 보다 크고 열은 `size` 보다 작으면 3사분면에서 재귀를 호출합니다
- `answer` 에 1, 2사분면 칸만큼 더해줍니다
- 행과 열이 모두 `size` 보다 크면 4사분면에서 재귀를 호출합니다
- `answer` 에 1, 2, 3사분면 칸만큼 더해줍니다
- `size` 는 재귀 호출될 때마다 값이 절반씩 줄어들게 되는데 `n` 이 1이 되면 재귀 호출을 종료합니다
- 제리의 pr
=> [동기] 20220913 백준 - Z 풀이 제출

후/20220910.java
요구사항대로 한땀한땀 구현하였습니다.
4-4단계의 요구사항을 잘못 이해하여 나머지 문자열의 `괄호 방향`이 아닌, 나머지 문자열 자체를 뒤집어서 뒤에 붙여서 통과를 못했습니다.
@ikjo93 의 리뷰덕에 솔브완료! 감사합니다 이크조!
=> 🔀 [후] 20220910 "프로그래머스 - 괄호 변환" 풀이 제출

제리/20220913-2.java
문제의 조건을 차근차근 맞춰가며 풀이했습니다. 국어를 못해서인지 문제의 뜻을 제대로 이해 못해서 삽질을 많이 했네요 ㅠㅠ
조건에 따라서 차근차근 풀이하면 풀 수 있는 문제였습니다!
=> 🔀 [제리] 20220913 "프로그래머스 - 괄호 변환" 풀이 제출

루시드/20220913_1.py
균형잡힌 문자열로 분리 -> 올바른 문자열일경우 재귀.. 문제 그대로 작성하면서 풀었습니다; ㅎㅎ
=> [루시드] 20220913 "프로그래머스 - 괄호 변환" 풀이 제출

피오/220912.java
1 ~ 4단계를 하나씩 따라가며 구현했습니다. 올바른 괄호인지 확인하는 `isProperBracket()`와 1 ~ 4단계를 진행하는
`proceedSteps()`를 을 재귀로 구현하였습니다. 구현도 구현인데 문제를 이해하는 데 시간이 오래 걸렸습니다..
=> [피오] 20220912 "프로그래머스 - 괄호 변환" 풀이중

피오/220910.java
처음에 모든 사분면을 다 재귀를 돌렸더니 시간초과가 나서 블로그와 익조 코드를 참고해서 힌트를 얻었습니다.
Z방향으로 순회하며 찾고자 하는 좌표가 어느 사분면에 있는지를 먼저 찾고, 
이전 사분면까지의 칸 수를 count에 더해준 후 해당 사분면에 대해서만 재귀를 호출하였습니다.
그러다 `length == 1`이 되는 시점에 한 칸 씩 반복문을 돌며 정확한 좌표를 찾아주었습니다.
=> [피오] 20220910 "백준 - Z" 풀이 제출

아더/20220911.java
처음에 풀고싶은대로 풀었다가 도저히 안되서 
다시 문제 요구사항을 한 단계씩 천천히 따라가며 구현했습니다.
물론 아래 조건의 내용을 잘못 이해해 그냥 문자열을 뒤집어 버리는 독해력을 발휘하긴 했습니다.
> 4-4. u의 첫 번째와 마지막 문자를 제거하고, 나머지 문자열의 괄호 방향을 뒤집어서 뒤에 붙입니다.
저의 독해력 선배님 @who-hoo 의 도움과 관전자 @Seokho-Ham 의 도움으로 해결했습니다!
=> 🔀 [아더] 20220911 "프로그래머스 - 괄호 변환" 풀이 제출

동기/20220919.java
- 1부터 진법 변환 연산을 합니다.
- 연산 결과를 `convertedNumeric` 이라는 String 변수에 추가해줍니다.
- `convertedNumeric` 길이가 게임에 참가하는 인원 `m`보다 크면 substring() 메서드를 이용하여 튜브의 차례의 문자를 추출합니다.
- 추출한 문자를 `answer`에 저장합니다.
- `answer`의 길이가 미리 구할 숫자의 개수 `t`와 같아지면 while문을 종료합니다.
=> [동기] 20220919 프로그래머스 - N진수 게임 풀이 제출

아더/20220912.java
처음엔 배열을 선언하고 풀어보려고 했는데 선배들의 메모리 초과를 보고 바로 지워버렸습니다.
다음으로는 재귀로 모든 곳을 돌며 카운트를 세려고 했으나 선배들의 시간 초과를 보고 정신차렸습니다.
마지막으로는 start와 end값을 구분하지 않고 하나만 받아서 처리하려 했으나 두뇌가 따라주지 않는군요.
결국 선배님(@who-hoo)의 코드를 참고하여 풀어보았습니다.......
=> 🔀 [아더] 20220912 "백준 - Z" 풀이 제출

루시드/20220919.java
해당 진수로 구성된 문자열을 만들고 직접 탐색! 간만에 자바하니 좋네요 🤯
=> [루시드] 20220919 "프로그래머스 - n진수 게임" 풀이 제출

아더/20220915.java
진법변환을 쉽게 할 수 있는 메소드인 `Integer.toString(number, n);`을 사용하면 쉽게 풀 수 있는 문제입니다.
미리 구해야 하는 길이를 최소화하기 위해 최대 `t * m`의 크기 정도만 미리 계산해두고 순서에 맞춰 한 글자씩 뽑습니다.
=> 🔀 [아더] 20220915 "프로그래머스 - n진수 게임" 풀이 제출

아더/20220918.java
요즘 코딩테스트를 여러 군데 봤는데 대부분 구현 문제가 많이 나오더라구요....... 백 투 기본합시다!
구현 문제인만큼 한 줄 한 줄 구현했습니다.
1. 먼저 도착시간 배열을 정렬합니다. 순서대로 처리하려구요.
2. 그 다음에 계산하기 편하게 모든 시간을 초 단위로 변경해서 큐에 넣었습니다.
3. 셔틀 기본 출발 시간, 잠 잘 시간, 타야 할 시간을 미리 초기화합니다.
4. 셔틀 운행 횟수만큼 반복하고 해당 회차에 탈 수 있는 사람들만 큐에서 뺍니다.(먼저 `peek()`으로 확인하고 탈 수 있다면 `poll()`)
5. 타야하는 마지막 시간 판단은 `(마지막 운행 셔틀 && 셔틀에 남은 자리없음)`으로 판단했습니다.
=> 🔀 [아더] 20220918 "프로그래머스 - 셔틀버스" 풀이 제출

동기/20220920.java
- 제리의 풀이를 보고 `PriorityQueue` 를 이용하여 해결할 수 있었습니다!
- 제리의 pr
=> [동기] 20220920 프로그래머스 - 셔틀버스 풀이 제출

동기/20220830.java
재귀를 이용하여 풀 수 있었습니다
1. 압축이 불가능(length == 1)할 때까지 재귀를 호출하였습니다
2. 현재 호출된 메서드에서 순회해야할 배열이 모두 같은 수로 이루어져있는지 체크합니다
3. 같은 수라면 압축되었기에 그 수가 0이면 0의 개수를 증가시키고, 1이면 1의 개수를 증가시킵니다
4. 같은 수가 아니라면 네 개의 정사각형으로 쪼개어 2번의 과정을 반복합니다.
4-1. 배열의 순회 시작점과 끝 지점을 이용해 쪼갠 네 개의 정사각형을 각각 순회하였습니다
5. 이 과정을 거치다 정사각형의 길이가 1이 되면 더이상 쪼갤 수 없기 때문에 해당 숫자를 체크하여 `return` 문으로 재귀 호출을 종료하고 0의 개수와 1의 개수를 반환합니다
여러분들의 풀이! 😇
=> [동기] 20220830 프로그래머스 - 쿼드 압축 후 개수 세기 풀이 제출

후/20220920_1.java
1. 구해야 하는 만큼만 `Integer.toString(int i, int radix)`를 이용하여 n진수의 숫자를 temp에 저장해둔 후,
2. 튜브가 미리 구하려는 만큼 튜브의 차례에 해당하는 문자만 answer에 이어 붙여주어 해결하였습니다.
O(n)
=> 🔀 [후] 20220920 "프로그래머스 - n진수 게임" 풀이 제출

후/20220920_2.java
문제부터가 이해가 잘 안가서 제리의 휘알을 참고하여 풀이하였습니다.
코드만 읽었을 때는 이해가 안가던 부분을 이해하려고 해당 코드가 어떤 의미일지를 생각하면서 리팩토링하면서 따라쳐봤어요!
[제뤼스 휘알](https://github.com/who-hoo/algorithm-study/pull/452)
=> 🔀 [후] 20220920 "프로그래머스 - 셔틀버스" 풀이 제출

동기/20220924.java
- `dp` 는 느무 취약하여 풀이 보고 이해하고자 했습니다
- 꼭대기부터 바닥까지 경로 중 가장 큰 값을 반환하는 문제였습니다
- 꼭대기 값을 미리 `메모제이션 배열`에 저장합니다
- 인덱스 1번부터 반복문을 돌면서 삼각형 `각 층의 첫번째 수의 연산 결과를 기록`합니다
- 기록한 연산 값을 기준으로 `같은 층의 수에서 나올 수 있는 연산 결과를 기록`합니다
- 메모제이션 배열 `마지막 층에 저장된 연산 결과 중 가장 큰 값`을 반환합니다
https://velog.io/@devsh/프로그래머스-정수-삼각형-with-Java
=> [동기] 20220924 프로그래머스 - 정수 삼각형 풀이 제출

동기/20220923.java
1. 파일명을 `head` `number` `tail` 로 분리합니다
2. 입력 받은 문자열을 `Arrays.sort()` 로 정렬합니다
3. 문자열을 정렬할 때 `Comparator` 를 사용하여 정렬 조건을 재정의합니다 (조건은 [블로그](https://velog.io/@hyeon930/프로그래머스-파일명-정렬-Java)를 참고하였습니다)
4. 정렬한 문자열을 반환합니다 
https://velog.io/@hyeon930/프로그래머스-파일명-정렬-Java
=> [동기] 20220923 프로그래머스 - 파일명 정렬 풀이 제출

익조/20220427.java
+ 각각의 CCTV별로 동작 방식을 구현했습니다.
+ 처음 사무실 데이터를 입력받을 때 CCTV 정보를 List에 저장합니다.
+ 처음 CCTV부터 마지막 CCTV까지 회전할 수 있는 모든 경우의 수를 따지면서 CCTV의 사각지대 최소 크기 개수를 도출했습니다.
=> [익조] 20220427 "백준 - 감시" 풀이 제출(2022. 7. 13. Update)

익조/20220502.java
+ 입력받은 문자열 s 중 '{'와 '}'를 모두 제거하여 숫자와 쉼표(,)만 남게 합니다.
+ 쉼표(,)를 기준으로 문자열을 분리(split)하여 문자열(숫자 문자열) 배열을 만듭니다. 
+ 각각의 숫자 문자열을 HashMap에 key 값으로 저장하면서 개수(value)를 카운팅(counting)합니다.
+ HashMap 크기 만큼의 배열을 만들어 HashMap key의 개수(value)가 가장 많을수록 첫 번째 인덱스에 가깝게, 개수가 가장 적을수록 마지막 인덱스에 가깝게 저장합니다.
O(N)
=> [익조] 20220502 "프로그래머스 튜플" 풀이 제출

익조/20220504.java
+ https://ikjo.tistory.com/214
=> [익조] 20220504 "백준 - 토마토" 풀이 제출

루시드/20220927.py
number를 추출 & 해당 number를 기준으로 정렬을 수행하고, 그 다음 string으로 정렬하였습니다.
=> [루시드] - 20220927 프로그래머스 파일명 정렬 풀이 제출

아더/20220922.java
`File`이라는 클래스를 만들고 생성자에서 문자열을 분리하며 저장할 수 있게 했습니다.
자체적으로 정렬조건도 구현해 실제 `solution`메소드에서는 파일명들을 순차적으로 리스트에 저장 후 sort해주었습니다.
`PriorityQueue`를 쓰려고 했으나 이상하게 정렬이 원하는대로 되지 않아 그냥 리스트로 받고 정렬해주었습니다.
[삽질]
중간에 number가 최대 5자리라는 조건을 확인하지 못하고 헤맸네요;;
=> 🔀 [아더] 20220922 "프로그래머스 - 파일명정렬" 풀이 제출

아더/20220927.java
`DP`로 접근했습니다!
1. 정수삼각형의 크기만큼 `DP배열`을 선언합니다.
2. 점화식을 세워 각 높이의 각 자리를 구합니다.
3. 이때 점화식은 3가지 경우로 분리됩니다.
4. 먼저 맨 앞 인덱스일 때는 인덱스가 `-1`이 되는 경우를 체크해줘야합니다.
5. 다음은 맨 뒤 인덱스일 때 인덱스가 해당 줄의 `Length`가 되는 경우를 체크합니다.
6. 두 가지 모두 해당하지 않는다면 윗 줄 인덱스의 -1 +1 중 큰 수와 해당자리를 더해 `DP`를 채워갑니다.
7. 마지막으로 제일 아랫줄을 대상으로 최댓값을 출력합니다.
`O(N^2)`
=> 🔀 [아더] 20220927 "프로그래머스 - 정수삼각형" 풀이 제출

아더/20220930.java
쉽지 않았네요. 데브매칭이 두려워집니다......
`Person` 클래스를 만들고 HashMap을 사용해 풀이했습니다!
=> 🔀 [아더] 20220930 "프로그래머스 - 다단계 칫솔 판매" 풀이 제출

루시드/20220927_2.py
=> [루시드] 20220927 프로그래머스 - 정수삼각형 풀이 제출

제리/20220920-2.java
크루원들의 줄을 서는 시간 String 입력을 분으로 변경한 이후에 PriorityQueue에 넣어 정렬한 이후, 크루원들을 버스에 태우면서 가장 늦은 시간을 구했습니다.
=> 🔀 [제리] 20220920 "프로그래머스 - 셔틀버스" 풀이 제출

제리/20220920-1.java
Integer.toString() 에서 자동으로 진법 변환을 해주어서 편하게 문제를 풀 수 있었습니다.
n진수에 맞게 변환하는게 핵심인 문제였는데 자바에서도 진법 변환 기능을 제공해서 쉽게 풀 수 있었네요.
자바에서 이런 기능을 제공하다니.. 감격스럽습니다.
=> 🔀 [제리] 20220920 "프로그래머스 - n진수 게임" 풀이 제출

동기/20221003.java
**Map 세팅**
- 해당 조직원이 가진 돈, 해당 조직원을 다단계로 이끈 상위 조직원을 가지는 `Report` 객체를 만들었습니다
- 조직원과 Report 객체를 갖는 `HashMap`을 만들었습니다
- `enroll` 의 길이만큼 반복하면서 enroll[i]의 상위 조직원은 referral[i]이기에 이 정보를 통해 `Map` 에 세팅해주었습니다
**판매 수익 로직**
- 판매에 성공한 조직원들을 기준으로 상위 조직원들에게 10%의 커미션을 주고자 했습니다
- for문을 한번씩 돌때마다 무한루프를 돌게합니다
- 무한루프는 조직원의 상위 조직원이 없다는 의미인 `-` 이거나 `money` 가 10 이하일 때 멈춥니다
- 무한루프를 통해 조직원의 `money` 값을 업데이트해줍니다
**결과 반환**
- 입력으로 주어진 `enroll` 의 순서대로 반환해야 합니다
- answer[i] 에 `enroll` 순서대로 결과 값을 반환하기 위해 `enroll[i]` 를 map의 key로 하여 값을 할당해주고 반환합니다
https://codingtalk.tistory.com/310
=> [동기] 20221003 프로그래머스 - 다단계 칫솔 판매

동기/20221004.java
- N 개의 초밥을 int형 배열 `arr`에 담습니다
- `Set` 자료형을 이용하여 `arr[i]` 부터 시작하여 `k`개까지 초밥을 Set에 담습니다
- 이 때 배열의 인덱스를 넘어가는 초밥도 탐색하기 위해 나머지 연산을 이용합니다
=> [동기] 20221004 백준 - 회전 초밥 풀이 제출

제리/20220927-01.java
전형적인 dp문제였습니다.
점화식을 계산하여 풀 수 있었습니다. 초기 값과 마지막에만 케이스가 다른데 배열을 크게 선언하여 초기만 다르게 세팅하고 마지막은 중간 값들과 동일하게 계산했습니다. (어차피 위에 들어 있는 값이 0이라 상관없음)
=> 🔀 [제리] 20220927 "프로그래머스 - 정수삼각형" 풀이 제출

제리/20220927-02.java
File 클래스를 만들어서 생성자를 통해 head, number, tail을 구분했습니다.
이후에 정렬 조건에 따라서 정렬을 진행했습니다.
초기에 `this.head = this.head.toLowerCase(Locale.ROOT);` 로 풀이하다보니까 모두 다 소문자가 되어 실패했었는데 새로운 변수로 비교를 하도록 변경하여 성공적으로 풀이할 수 있었습니다.
=>  🔀 [제리] 20220927 "프로그래머스 - 파일명 정렬" 풀이 제출

루시드/20221004_2.py
map을 통해 [부모, 총 벌이]로 등록한 후, share가 1보다 작아질 때까지 부모를 찾아 이익을 분배하였습니다.
=> [루시드] 20221004 "프로그래머스 - 다단계 칫솔 판매" 풀이 제출

제리/20221004-1.java
Map을 통해 tree 를 설정해주었습니다.
자식이 부모를 가르키고 자식은 단 하나의 부모노드 또는 부모노드가 존재하지 않기 때문에 Map으로 자식노드에서 부모노드를 가르키도록 했습니다.
이후에 seller가 판 돈을 기준으로 1원 (더 이상 부모 노드로 갈 필요가 없는 경우)까지 이익이 될 때까지 부모에게 돈을 분배하는 방식으로 구현했습니다.
=> 🔀 [제리] 20221004 "프로그래머스 - 다단계 칫솔 판매" 풀이 제출

후/20221004_1.java
이름, 자신을 추천한 Seller, 이익을 가지는 클래스 Seller를 정의한 후, 
이름으로 O(1)의 시간복잡도로 Seller를 찾을 수 있도록 이름을 Key, Seller를 Value로 갖는 HashMap을 선언하여 셀러를 관리하였습니다.
distributeProfit 메서드를 이용하여 연쇄적으로 추천인과 이익을 분배하도록 하였습니다.
O(N)...?!
=> 🔀 [후] 20221004 "프로그래머스 - 다단계 칫솔 판매" 풀이 제출

20221011.py
=> [루시드] 20221011 백준 - 종이의 개수 풀이 제출

아더/20221011.java
분할정복으로 접근해 해결할 수 있는 문제입니다.
종이의 크기는 계속 3의 제곱수로 주어지므로 한 번의 반복마다 3으로 나누어 계산했습니다.
나눈 후 9개의 숫자가 모두 같은 숫자인지 판단하는 메소드를 통해 해결했습니다.
=> 🔀 [아더] 20221011 "백준 - 종이의 개수" 풀이 제출

동기/20221006.java
- 네모를 어떻게 회전시켜야할지 몰라 아이디어는 아래 블로그를 참고하였습니다 😩
https://yline.tistory.com/3
- 어떻게 돌릴지 보고도 하나씩 옮기는 로직을 두뇌 풀가동하여  작성하는데도 시간이 오래 걸리네요 . . . ..  .
=> [동기] 20221006 프로그래머스 - 행렬 테두리 전환하기 풀이 제출

동기/20221011.java
- 프로그래머스 쿼드압축후개수세기 문제랑 비슷하다고 판단하여 당시 코드를 템플릿 삼아 9개로 나누는 거만 바꾸니 풀 수 있었습니다
=> [동기] 20221011 백준 - 종이의 개수 풀이 제출

제리/20221011-2.java
=> 🔀 [제리] 20221011 "백준 - 종이의 개수" 풀이

루시드/20221004.py
투 포인터 & map을 활용하여 풀었습니다.
left 삭제 & right 추가하고 map key의 길이를 통해 종류의 수를 계산하였습니다.
=> [루시드] 20221004 "백준 - 회전 초밥" 풀이 제출

동기/20221017.java
- 너무 쉽다했더니 역시나 시간초과...
- 누적합을 이용해서 풀어야하는 DP 문제였읍니다
- 이전 인덱스 값을 더하여 누적 값으로 표를 채웁니다
- x1부터 x2까지 for문을 돌고 y2 에서 y1 - 1 을 뺀 값이 구간합이 되기에 그 값을 반환합니다
- 익조의 PR...🫡
=> [동기] 20221017 백준 - 구간 합 구하기 5 풀이 제출

후/20221015.java
1. 구할 수 있는 컬럼의 전체 조합을 구함.
2. 구한 컬럼 조합으로 구성된 tuples를 만들어서, 유일성과 최소성 검사
- 유일성 검사 : 튜플 순회하면서 중복 있는지 검사
- 최소성 검사 : 컬럼 조합에서 컬럼 하나씩 제외해서 tuples 새로 만들어서 유일성 다시 검사
---
엄청 무식하게 풀었는데, row & col 개수가 적어서 통과했네요...
조합 구하는 것도 다 까먹어서 인터넷 코드 참조하였습니다...히히... 
측정할수없는 무식함... 아도겐 어게인
[조합 구할때 참고한 코드](https://gyuwon95.tistory.com/136)
=> 🔀 [후] 20221015 "프로그래머스- 후보키" 풀이 제출

아더/20221017_2.java
N과 M의 범위를 생각해보면 최대 10억 번의 연산이 나올 수 있습니다. 
따라서 평범하게 계산하는 것이 아닌 누적합의 개념으로 각 자리에 그 자리까지 합을 계산해놓고 제외되는 부분을 빼는 형식으로 계산합니다.
=> 🔀 [아더] 20221017 "백준 -  구간 합 구하기 5" 풀이 제출

루시드/20221018.py
=> [루시드] 20221018 "프로그래머스- 후보키" 풀이 제출

제리/20221018-2.java
누적합을 dp[][]로 가지고 있어서 바로 계산할 수 있도록 했습니다.
=> [제리] 20221018 백준 - 구간 합 구하기 5 풀이 제출

제리/20221018-1.java
=> [제리] 20221018 프로그래머스 - 후보키 풀이중

아더/20221021.java
1. 먼저 방향 문자열을 char배열로 변환해 한 방향씩 처리합니다.
2. 맵의 전체 크기는 `11 x 11 x 4`로 초기화합니다. 여기서 4는 해당 위치로 들어오는 방향을 의미합니다.
3. 방향을 미리 정의한 숫자로 변환시킨 후 새로운 좌표 값을 계산합니다. 이때 들어오는 방향을 계산하기 위해 `int fromDir = (change + 2) % 4;` 의 공식을 사용합니다.
4. 맵의 범위를 벗어나는지 판단하고 이미 방문했거나 반대 경로를 이미 방문했던 적이 있다면 `continue` 합니다.
5. 4번을 통과한다면 방문체크를 해주고 `answer`에 1을 더합니다.
`O(N)`
=> 🔀 [아더] 20221021 "프로그래머스 - 방문 길이" 풀이 제출

아더/20221024.java
처음에는 `DP`인줄 모르고 구현했는데 테스트케이스만 통과하고 제출하니 7점 받았습니다....
`DP`인걸 깨닫고도 점화식 세우는 데 한참 걸렸습니다. 멍청쓰
1. DP 배열을 2차원으로 사용했습니다. [0]은 첫 번째 스티커에서 시작한 배열이며 [1]은 두 번째 스티커부터 시작한 배열입니다.
2. 위의 조건을 수행하기 위해 `i가 1`일 때와 `i가 length - 1`를 나누어 판별했습니다.
3. 위의 두 가지 케이스를 제외한 나머지 점화식은 다음과 같습니다
- `DP[i][0] = Math.max(DP[i - 1][0], DP[i - 2][0] + sticker[i]);`
- `DP[i][1] = Math.max(DP[i - 1][1], DP[i - 2][1] + sticker[i]);`
4. 마지막으로는 [0]과 [1] 중 더 큰 값을 출력합니다.
`O(N)`
=> 🔀 [아더] 20221024 "프로그래머스 - 스티커모으기2" 풀이 제출

익조/20220811.java
+ LCS 알고리즘은 처음 들어봤네요 👀 아래 기술 블로그 자료를 참고하면서 풀이했습니다.
+ 입력받은 문자열 A와 문자열 B를 문자 배열로 변환한 후 
+ 2차원 배열 상에 두 문자열에 대한 문자 하나하나 비교하도록 했습니다.
+ 이때, 두 문자가 같으면 해당 배열에 1을 할당하고, 다를 경우 왼쪽 칸과 위쪽 칸 중 가장 큰 값을 할당해주도록 했습니다.
+ 이러한 로직에 대한 해석은 아래 참고 자료에 그림과 같이 설명되어 있어 이해하는데 많은 도움이 되었습니다.
O(N^2)
+ <a href="https://velog.io/@emplam27/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-LCS-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Longest-Common-Substring%EC%99%80-Longest-Common-Subsequence">그림으로 보는 LCS 알고리즘</a>
=> [익조] 20220811 "백준 - LCS" 풀이 제출 

익조/20220815.java
+ 백트래킹을 활용하여 고장나지 않은 리모컨 버튼으로 만들 수 있는 모든 채널에 대해 일일이 타겟 채널과 일치하는지 검증해주도록 했습니다.
+ 일단 문제 해결 자체만을 위해 다소 비효율적인 방법으로 풀이해보았는데, 최적화 예정입니다!
+ 문제 제한 시간은 2초인데, 3초 나왔는데도 통과는 되긴하네요..
=> [익조] 20220815 "백준 - 리모컨" 풀이 제출

포키/20220823.java
답안을 보고 냈습니다. 직접 다시 구현해 볼 예정입니다.
=> [포키] 20220823 백준 dslr  풀이중

포키/20220829.js
재귀 함수를 통해 문제 해결
1. 각 영역의 숫자들이 같은지 검사한다.
2. 같을 경우 해당 값으로 카운트
3. 다를 경우 반으로 쪼개서 해당 작업 실행.
=> [포키] 20220830 - 프로그래머스 쿼드압축 후 개수 세기 풀이 제출

포키/20220830.java, 포키/20220830.js
투포인터를 활용해서 풀었습니다.
- 두개의 큐를 합쳐서 하나의 배열을 만듭니다.
- 두개의 큐의 합을 구해서 절반을 나눈 값을 타겟값으로 둡니다.
- 한쪽 큐의 값에 디큐, 인큐를 진행하며 타겟값과 동일해졌을 경우 횟수를 반환합니다.
=> [포키] - 20220830 프로그래머스 두 큐 합 같게 만들기 풀이 제출

포키/20220904.java
=> [포키] 20220904 프로그래머스 배달 풀이 제출

포키/20220906.java
1. 문자열들을 2문자씩 끊어서 list에 담아준다.
- 여기서 2개의 문자를 돌면서 문자열만 들어갔는지 검사한다.
2. 교집합 구하면서 한쪽 list에서 교집합은 제거해준다.
3. 교집합과 합집합을 나눈 뒤 지정해준값을 곱해서 반환한다.
=> [포키] 20220906 프로그래머스 뉴스 클러스터링 제출

포키/20220910.java
~~조건을 보고 일단 구현을 해보았지만 현재는 5개만 통과하네요;;
잊을까봐 미리 제출해둡니다;;~~
->   )))))(((((( 를 넣어보니까 u를 만드는 과정에서 if문 조건이 틀렸었다는걸 발견했네요!
재귀를 사용해서 문제를 해결했습니다.
=> [포키] 20220910 프로그래머스 괄호변환 풀이완료

포키/20220920.java
1. 먼저 전체 나올 수 있는 문자열을 구합니다.
2. while문을 돌며 사용자의 차례에 있는 문자를 answer 변수에 추가해줍니다.
=> [포키] 20220920 프로그래머스 - N진수 게임 풀이

포키/20220926.java
Comparable 인터페이스를 구현한 File 클래스를 만들고 Collections.sort로 정렬을 했습니다.
comparTo 메서드 내에서는 head, number, index 순으로 정렬을 하도록 했습니다.
=> [포키] - 20220926 프로그래머스 파일명 정렬 풀이 제출

포키/20220927.java
2중 for문을 사용하여 값을 누적해나간뒤, 마지막 행에 대해 stream으로 최대값을 작성했습니다.
- 0일 경우 무조건 이전 배열의 0번 인덱스 값
- i와 j가 같을 경우 [i-1][j-1]
- 나머지 경우 이전 배열의 j-1 과 j를 비교해서 큰값
=> [포키] 20220927 프로그래머스 - 정수삼각형 풀이 제출

포키/20220925.java
문제가 이해가 되지 않아 제리의 pr을 통해 코드를 이해하고 작성했습니다.
=> [포키] 20220928 프로그래머스 셔틀버스 풀이 제출

포키/20220929.java
map의 순서를 보장하기 위해서 LinkedHashMap을 사용했습니다.
각각의 Seller 객체를 만들고 자신의 추천인 필드가 null일때까지 추천인의 메서드를 반복적으로 호출하는 방식으로 구현했습니다.
=> [포키] 20220929 프로그래머스 - 다단계 칫솔팔기 풀이 제출

포키/20221004.java
List에 초밥을 순서대로 넣은 뒤 for문으로 각 위치부터 k만큼 먹도록 했습니다.
각 반복문마다 d의 최대값인 3000길이의 배열을 만든 뒤 해당 index의 초밥이 처음일 경우 count에 1을 더해 주었고, 쿠폰으로 먹는 초밥도 동일한 방법으로 검사했습니다.
이후 result와 현재 count를 비교하여 큰 값을 저장했습니다.
=> 🐵 [포키] 20221004 백준 회전초밥 풀이 제출

포키/20220809.java
투포인터를 사용했습니다.
1번 포인터가 2번 포인터를 넘어가지 않고, 2번 포인터가 n보다 작을 경우동안 while문을 반복했습니다.
sum변수에 하나씩 값을 추가했고 2번 포인터를 올렸고, sum이 s값을 넘어가면 1번 포인터값을 하나씩 당기는 형식으로 풀었습니다.
=> 🐵 [포키] 20220809 백준 부분합 풀이 제출 (기존 pr에 추가가 되지 않아 새로운 pr로 제출합니다)

포키/20220607.java
Set과 Map을 사용하여 값을 저장했습니다.
처음에 순서보장이 안되는 HashSet을 사용해서 헤맸네요. 
그래서 LinkedHashSet으로 변경한 뒤 stream으로 추천을 제일 적게 받은 id를 찾아서 제거하도록 했습니다.
=> 🐵 [포키] 20220607 백준 후보 추천하기 풀이 제출(기존 pr에 추가가 되지 않아 새로운 pr로 제출합니다)

포키/20221008.java
단순하게 조건문을 여러개 걸어서 돌렸습니다.
각 꼭지점일 경우에 대해서는 방향을 돌리도록 조건을 걸었습니다.
=> [포키] 20221008 프로그래머스 행렬 테두리 회전하기 풀이

포키/20221010.java
1. 현재 위치를 베이스 값으로 지정해두고 지정한 범위까지 순회하며 각 위치의 값과 베이스 값이 같은지 비교합니다.
2. 같을 경우 HashMap에 해당 값의 카운트를 1 올립니다.
3. 다를 경우 9등분 해서 동일한 로직을 실행합니다.
=> [포키] 20221010 백준 종이의 개수 풀이

포키/20221017.java
문제 이해 후 풀이를 도저히 모르겠어서 아래 블로그의 설명을 보고 코드를 작성했습니다.
[블로그 링크](https://small-stap.tistory.com/38)
=> [포키] 20221018 프로그래머스 후보키 풀이 제출

포키/20221024.java
3차원 배열을 사용하여 각 지점에서 입력방향을 방문했는지 체크하며 넘어갔습니다.
각각의 방향은 Enum으로 만들어서 사용했습니다.
=> [포키] 20221025 프로그래머스 방문길이 풀이

포키/20221018.java
아더의 도움 덕분에 점화식을 빠르게 이해할 수 있었습니다.
=> [포키] 20221018 백준 구간 합 구하기 풀이 제출

제리/20221025-1.java
방향에 따라서 동일하게 체크하기 위해서 규칙을 생성했습니다.
이동 경로에 순서를 부여해서 위에서 아래, 아래에서 위로 이동해도 동일한 경로로 인식하는 것이 중요하다보니 String으로 순서를 부여해서 (0, 0) -> (1, 0) 이동 시 0010 으로 생성, (1, 0) -> (0, 0) 이동 시에도 0010으로 생성되도록 규칙을 만들어 Set으로 중복되지 않는 경로를 구했습니다.
=> 🔀 [제리] 20221025 "프로그래머스 - 방문 길이" 풀이 제출

익조/20220901.java
앗..! 이미 풀었던 문제였습니다 😅
+ 다익스트라를 통해 해결할 수 있었습니다.
+ 1번 마을에서 출발했을 때 각각의 마을에 도착할 수 있는 최소 비용을 구하고, K 시간 이하로 배달이 가능한 마을들을 추출했습니다.
O(도로 정보의 개수 * logN)
+ 도로 정보의 개수 : 1이상 2000 이하
=> [익조] 20220901 "프로그래머스 - 배달" 풀이 제출

아더/20221103.java
전형적인 dfs 문제였고 특이한 엣지케이스도 없습니다!
=> 🔀 [아더] 20221103 "백준 - 그림" 풀이 제출

아더/20221106.java
이번 문제도 dfs 문제였습니다! 
같은 방식으로 풀이했습니다.
=> 🔀 [아더] 20221106 "백준 - 단지번호붙이기" 풀이 제출

동기/20221107.java
- 배열을 dfs로 순회하고자 했습니다
- 방문한 적이 없으며 좌표에 값이 `1`인 곳을 기점으로 dfs를 시작합니다
- dfs를 돌때마다 `count`를 증가시켜주어 단지 내의 집의 수를 파악합니다
- dfs 방문이 끝나면 count를 `list` 에 추가합니다
- 다시 또 방문한 적이 없으며 좌표 값이 `1`인 곳을 기점으로 dfs를 시작합니다
- 배열 순회가 끝나면 `list`의 사이즈로 단지 개수를 알게되고, `list`를 정렬하여 오름차순으로 저장된 단지를 `StringBuilder`에 담아 반환합니다
O(n^2)
=> [동기] 20221107 백준 - 단지번호 붙이기 풀이제출

동기/20221104.java
- dfs로 순회하여 그림의 개수와 가장 큰 너비의 그림을 반환하였습니다
=> [동기] 20221104 백준 - 그림 풀이 제출

제리/20221101-01.java
매번 외부를 체크한 이후에 치즈와 외부가 맞닿아있는 부분을 체크한 이후에 제거를 반복하며 풀이했습니다.
=> [제리] 20221101 백준 - 치즈 풀이

익조/20220506.java
+ 입력받은 사용자별 기록들(String[] record)에 대해 순서대로 List 자료구조에 add 합니다.
+ 각각의 사용자별 기록들에 대해 순서대로 split를 통해 상태(Enter, Leave, Change), 아이디, 닉네임을 분리합니다.
+ 이때 별도의 UserState 구조체를 선언하여 사용자의 상태와 아이디를 저장하도록 했습니다. 다만 Change의 경우 기존 사용자의 닉네임을 바꾸는 작업이므로 UserState에 포함시키지 않습니다.
+ 아울러 별도의 HashMap을 선언하여 사용자의 아이디별로 닉네임을 저장하도록 했는데, 이는 추후 Enter와 Change 작업으로 인해 사용자 아이디별로 닉네임이 바뀔 수 있기 때문입니다.
+ 최종적으로 도출된 List<UserState> 자료구조를 순회하여 Enter 상태일 경우 `{nickName}님이 들어왔습니다.` 형식으로, Leave 상태일 경우 `{nickName}님이 나갔습니다.` 형식으로 String 배열에 담아 반환합니다.
=> [익조] 20220506 "프로그래머스 - 오픈채팅방" 풀이 제출

익조/20220902.java
앗 이 문제도 풀었던 문제네용..😅
접근 방법은 따로 정리했었습니다~
+ https://ikjo.tistory.com/279
O(N)
=> [익조] 20220902 "프로그래머스 - 뉴스 클러스터링" 풀이 제출

루시드/20221122_2.java
X의 값과 현재 값을 뺀 값(X - i)이 1일 경우에만 result를 올립니다. 매번 i를 1로 변경해주기 때문에 같은 쌍이 중복 처리되지 않습니다.
=> [루시드] 20221122 "백준 - 두 수의 합" 풀이 제출

익조/20220910.java
+ 이전에 접근 방법을 정리했었습니다 ㅎㅎ
+ https://ikjo.tistory.com/232
+ 5월달에 풀었던 거라 리셋하고 다시 한 번 풀어보겠습니다 ㅎㅎ!
```Java
// 2022. 9. 10. 토 재도전 풀이 (코드가 더 길어졌다...?!)
class Solution {
public String solution(String p) {
return conversion(p);
}
private String conversion(String s) {
if (s.isEmpty()) {
return s;
}
String[] splitString = getSplitString(s);
StringBuilder result = new StringBuilder();
if (checkCorrectString(splitString[0])) {
result.append(splitString[0]);
result.append(conversion(splitString[1]));
} else {
result.append("(")
.append(conversion(splitString[1]))
.append(")")
.append(reverse(splitString[0]));
}
return result.toString();
}
private String[] getSplitString(String w) {
int count = 0;
StringBuilder u = new StringBuilder();
String v = "";
char[] chars = w.toCharArray();
for (int i = 0; i < …
```
=> [익조] 20220910 "프로그래머스 - 괄호 변환" 풀이 제출

익조/20220915.java
+ 예전에 풀었던 문제였는데, 이번에 다시 한 번 풀어봤습니다 ㅎㅎ
+ 최초 0이라는 숫자부터 n진수로 변환한 후 자기 차례에 맞는 비트를 인덱스로 뽑아 결과값에 추가해주었습니다.
+ 저 같은 경우 n진수 변환 로직을 직접 구현했는데, Integer 래퍼 클래스의 `public static String toString(int i, int radix` 메서드를 사용하면 쉽게 변환이 가능한 것 같습니다..ㅋㅋ..
+ 앞선 방식을 미리 구할 숫자 t개가 될 때까지 반복합니다.
=> [익조] 20220915 "프로그래머스 - n진수 게임" 풀이 제출

루시드/20221129_2.java
=> [루시드] 20221129 백준 - 연산자 끼워넣기 풀이 제출

아더/20221118.kt
코틀린으로 풀이해봤습니다.
N의 범위는 100,000입니다. 완전탐색을 사용하면 시간초과가 발생합니다.
따라서 `이분탐색`을 활용합니다.
이분탐색을 해야하기에 먼저 배열을 정렬합니다.
다음으로 이분탐색 로직을 수행하면 `(i, j), (j, i)` 쌍을 구할 수 있습니다.
조건에 `i < j`라는 조건이 있기 때문에 구한 정답에서 `/ 2 처리`를 해줍니다.
=> 🔀 [아더] 20221118 "백준 - 두 수의 합" 풀이 제출

동기/20221128_1.java
- 사다리 타야하는 상황을 배열을 이용해 저장합니다
- `bfs` 를 사용하여 주사위 숫자인 1부터 6까지 반복하여 위치를 갱신합니다
- 갱신한 위치가 사다리를 타게 되는 상황인지, 아닌지 확인합니다
- 주사위를 굴린 횟수를 업데이트하고 Queue에 갱신한 위치를 넣어주어 너비 우선 탐색을 반복합니다
O(V+E)
블로그를 참고하였는데 며칠 전에 풀고 링크를 잊어버렸읍니다
=> [동기] 20221128 백준 - 뱀과 사다리 게임 풀이 제출

아더/20221125.java
전형적인 순열로 해결하는 문제였습니다.
순열로 숫자들을 배열할 수 있는 경우의 수를 모두 구하고 한 번 다 뽑았을 때마다 
최댓값과 최솟값을 계산해 저장해놓습니다.
=> 🔀 [아더] 20221125 "백준 - 연산자 끼워넣기" 풀이 제출

아더/20221203.java
=> 🔀 [아더] 20221203 "구름 - 소수 찾기" 풀이 제출

익조/20220516.java
+ 우선 각각의 빛의 경로 사이클을 구분하는 방법은 특정 노드 위치(행 : row, 열 : col)에서의 특정 방향(동, 서, 남, 북)을 통해 구분하는 방법이 있습니다.
+ 예를 들어 A 사이클과 B 사이클이 있다고 했을 때 A 사이클의 모든 노드에서의 방향과 B 사이클의 각각의 모든 노드에서의 방향은 중복되는 것이 하나도 없습니다. `(A[i][j][k] != B[i][j][k])` 만일 하나라도 같다면 A 사이클과 B 사이클은 같은 사이클일 수밖에 없는 것입니다.
+ 이러한 점을 고려하여 모든 특정 노드 위치에서의 모든 방향들을 완전 탐색하여 빛의 경로 사이클을 구할 수 있는데, 이때 탐색시마다 특정 노드에서의 특정 방향에 대해 방문할 때마다 방문처리를 해주면 다음 사이클을 탐색 시에 중복되지 않고 사이클을 탐색할 수 있습니다.
+ 이러한 특정 노드 위치(행 : row, 열 : col)에서의 특정 방향(동, 서, 남, 북)에 대한 방문 처리 정보는 3차원 boolean형 배열을 통해 나타낼 수 있습니다.
+ 하나의 사이클 탐색을 종료시키기 위한 조건으로는 맨 처음 노드의 위치와 방향을 기억해놓았다가(startPonints) 추후 탐색 시 동일한 위치와 방향을 가리킬 경우 종료시키도록 했습니다.
+ 참고로 해당 문제를 재귀함수를 통해 정답을 도출하려고 했으나, 런타임 에러(Stack Overflow)가 나와, 반복문으로 접근했습니다.
O(N^2 ) (N : grid의 길이)
=> [익조] 20220516 "프로그래머스 - 빛의 경로 사이클" 풀이 제출

익조/20220922.java
+ 예전에 풀었던 문제였는데, 다시 한 번 풀어봤습니다 ㅎㅎ
+ 입력받은 파일명 하나하나를 순회하면서 `head, number, tail`을 각각 추출하여 별도의 File 클래스 구조체를 선언하여 File 객체를 만들어주도록 했습니다.
+ 그리고 File 클래스가 Comparable 인터페이스를 구현하도록 하여 문제에서 요구하는 조건대로 정렬되도록 했습니다.
+ 이렇게 생성된 File 객체들을 최종적으로 정렬한 이후 결과값으로 반환해주었습니다.
=> [익조] 20220922 "프로그래머스 - 파일명 정렬" 풀이 제출

익조/20221210.java
+ 각 노드별 데이터 값을 배열에 저장한 후(지워진 값을 메꿀 임의의 수 포함) 정렬하여 중간 값을 루트 노드로 정했습니다.
+ 이후 루트노드 왼쪽 서브트리, 오른쪽 서브트리별로 분할정복을 통해 이진 검색 트리를 구성하도록 했습니다.
+ 이진 검색 트리를 구성 완료 후 문제에서 요구하는 후위순회를 하여 결과를 출력했습니다.
```
SW 마에스트로는 이런식으로 알고리즘 대회도 진행하나보네요 ㄷㄷ 👍👍
```
=> [익조] 20221210 "백준 - 이가 빠진 이진 트리" 풀이 제출

익조/20221207.java
+ 프로그래머스 몇 주전에 출제 됐던 따끈따끈한 그리디(?) 문제군요 ㅎㅎ (이미 풀었던 문제입니다)
+ 입력받은 귤 데이터를 종류별 개수를 맵에 저장한 후 내림차순으로 정렬하여 개수가 가장많은 종류의 귤의 수를 k에서 빼주어 `서로 다른 종류의 수의 최솟값`을 구했습니다.
=> [익조] 20221207 "프로그래머스 - 귤 고르기" 풀이 제출

익조/20221203.java
+ 에라토스테네스의 체를 이용하여 소수를 구해 정답을 도출했습니다.
=> [익조] 20221203 "구름 - 소수 찾기" 풀이 제출

익조/20221125.java
+ 연산자를 입력받은 후, 순열(백트래킹으로 구현)을 통한 각각의 경우의 수에 대해 연산 작업을 해주도록 했습니다.
=> [익조] 20221125 "백준 - 연산자 끼워넣기" 풀이 제출

익조/20221124.java
+ BFS를 통해 주사위 면이 1 ~ 6 이 나왔을 때 경우에 대해 순차적으로 탐색해주도록 했습니다.
+ 이때 뱀과 사다리 정보를 ~~맵~~ 배열에 저장하였고 탐색 시 이를 활용하도록 했습니다.
=> [익조] 20221125 "백준 - 뱀과 사다리 게임" 풀이 제출

익조/20221119.java
+ 접근 방법을 여기다가 주저리 적었다가 너무 난잡해서 블로그에다가 정리해보았습니다. ㅎㅎ
+ [[프로그래머스] 보행자 천국 - Java](https://ikjo.tistory.com/363)
O(NM)
=> [익조] 20221119 "프로그래머스 - 보행자 천국" 풀이 제출

익조/20221117.java
+ 정렬한 후 양 끝에 두 개의 포인터를 조절하면서 두 수의 합이 x인 개수를 세도록 했습니다
=> [익조] 20221117 "백준 - 두 수의 합" 풀이 제출

익조/20221112.java
+ 앗.. 이 문제도 2달 전에 풀었던 문제네요...😅
+ 백트래킹을 이용하여 주어진 치킨집 중 m개의 치킨집을 골라, 치킨 거리를 구하기를 반복해서 최소 치킨 거리를 구했습니다.
=> [익조] 20221112 "백준 - 치킨 배달" 풀이 제출

익조/20221110.java
+ 앗 2달 전에 풀었던 문제였습니다 ㅎㅎ (당시에 엄청 애먹었던 문제였습니다...)
+ 나름대로 재밌었던 문제였어서 따로 풀이를 정리해보았었습니다
+ https://ikjo.tistory.com/342
=> [익조] 20221110 "백준 - 벽 부수고 이동하기" 풀이 제출

익조/20221106.java
+ 오 이번주는 그래프 탐색 특집이군요 ㅋㅋ!!
+ DFS를 통해 단지수와 단지별 주택수를 도출했습니다
+ 이 문제는 예전에 풀었던 거라 예전 풀이 그대로 제출합니다!! ㅎㅎ
=> [익조] 20221106 "백준 - 단지번호붙이기" 풀이 제출

익조/20221103.java
+ 깊이 우선 탐색을 통해 그림의 개수와 각각의 그림 중 최대 크기 영역을 구해주도록 했습니다.
+ 너비 우선 탐색을 통해서도 무난히 구해낼 수 있긴한데 보통 두개를 모두 이용할 수 있는 상황에선 그나마 코드 길이가 짧은 깊이 우선 탐색을 선택하는 편입니다!
=> [익조] 20221103 "백준 - 그림" 풀이 제출

익조/20221027.java
+ 제가 제일 좋아하는 유형의 문제입니다 😊
+ 치즈 바깥 공기와 치즈 내부 공기를 구분하는 것이 키포인트였던 것 같습니다.
+ 문제 마지막 줄에 `모눈종이의 맨 가장자리에는 치즈가 놓이지 않는 것으로 가정한다.` 라는 문구를 통해 바깥 공기와 내부 공기를 구분할 수 있었습니다.
+ dfs를 통해 바깥 공기를 따로 선언해주었습니다.
+ 이후에는 바깥 공기와 노출면이 2개 이상있는 치즈를 차례대로 제거해주면서 시간을 카운팅해주었습니다.
O(NM)
=> [익조] 20221027 "백준 - 치즈" 풀이 제출

익조/20221021.java
+ Set을 이용하여 이미 갔던 길을 이중 카운팅 하지 않도록 했습니다.
+ 다만, x -> y 갈 때와 y -> x 갈 때 이중 카운팅이 될 수 있으므로, 이 경로를 모두 Set에 add시킨 다음, 
+ 최종 결과값을 반환할 때 2를 나눠주도록 했습니다.
=> [익조] 20221021 "프로그래머스 - 방문 길이" 풀이 제출

익조/20221015.java
+ 앗 3주전에 풀었던 문제입니다 ㅎㅎ..  누적합을 이용하면 구간합을 구하기 용이하다는 속성을 이용했습니다.
=> [익조] 20221015 "백준 - 구간 합 구하기 5" 풀이 제출

익조/20221014.java
+ 예전에 풀었던 문제입니다 ㅎㅎ(프로그래머스 level 2는 다 풀었어요) 우선 바쁜대로 이전에 풀었던 풀이 그대로 제출합니다 😭 
+ 개인적으로 되게 힘겹게 풀었던 문제라 당시 풀이가 무지성 그 자체인 상태입니다 👀 (리팩토링 시급)
+ 접근 방법은 백트래킹을 통해 키가 될 수 있는 모든 조합에 대해 각각 유일성과 최소성을 만족하는지 일일이 검증해주도록 했습니다.
=> [익조] 20221014 "프로그래머스 - 후보키" 풀이 제출

익조/20221011.java
+ 주어진 종이 영역을 행과 열에 대해 각각 1/3씩 9개 영역으로 나눠 분할 정복시켰습니다.
=> [익조] 20221011 "백준 - 종이의 개수" 풀이 제출

익조/20221007.java
+ for문으로 배열을 회전 시키려고 했는데, 한쪽 면에서 회전하면 다른쪽 면 회전 시킬 때 영향을 주기 때문에,
+ 기존 행렬(2*2 배열)의 사본을 별도로 생성해서 이를 이용했습니다.
=> [익조] 20221007 "프로그래머스 - 행렬 테두리 회전하기" 풀이 제출

익조/20220923.java
+ 부모 트리에서 자식 트리로 넘어갈 때 메모라이징된 가장 큰 값을 가진 부모 노드의 값으로 누적 합산해주었습니다.(Bottom-up)
+ 이때 특정 계층(2계층 이상)에서 양 끝 사이드에 있는 노드는 부모 노드가 하나이므로 그 값을 그대로 합산해줍니다.
+ (보완사항) 저 같은 경우 별도 메모라이징할 배열을 생성해주었는데, 모범 답안(다른 사람의 풀이)을 보니 별도 배열 생성 없이도 기존 triangle 배열을 재활용해도 될 것 같습니다. 😅
=> [익조] 20220923 "프로그래머스 - 정수 삼각형" 풀이 제출

익조/20220919.java
+ 일단 문제(특히 입출력 예제 2번)를 이해하는데 엄청 오래걸렸습니다..ㅋㅋ
```
* 입출력 예제 2에 대한 이해
n = 2, t = 10, m = 2일 때,
최초 9시에 2명을 태울 수 있는데, 이때 중요한 것은 8시에 온 사람 한명만 태운다는 것입니다.
저 같은 경우에는 9시 9분에 온 사람도 태울 수 있다고 착각했습니다. 😅
그리고 9시 10분에 오는 다음 셔틀 버스가 9시 9분에 온 사람과 9시 10분에 온 사람을 태울 수 있습니다.
```
+ 아무쪼록 이 문제의 핵심 포인트는 주인공 콘이 `최대한 마지막 셔틀 버스 도착 시간 '정각'에 맞춰 도착하도록` 해야하는 것이었습니다.
+ 저 같은 경우에는 그래서 `타임테이블(timetable) 배열을 오름차순으로 정렬`한 후 가장 일찍 온 크루부터 첫 번째 셔틀 버스에 태운 후(셔틀 버스 도착 이전 or 정각 도착 크루 한정), 못 탄 사람은 그 다음 셔틀 버스에 태우도록 했습니다.(이때 못 타는 사람들도 발생할 수 있습니다.)
+ 최종적으로 주인공 콘은 `마지막 셔틀 버스`에 탈 수 있는 사람의 여분이 있는 경우 `버스 도착 시간`을 반환하도록 했고, 여분이 없을 경우 `가장 마지막에 탄 사람 보다 1분 적은 시간`을 반환하도록 했습니다.
> 문제에서 주어진 조건 : `단, 콘은 게으르기 때문에 같은 시각에 도착한 크루 중 대기열에서 제일 뒤에 선다.`
+ 흐름도 : 크루들의 줄 서기 → 버스 준비 → 크루들의 버스 탑승 → 콘의 마지막 버스에 낑겨 타기(자리 없으면 한명 제끼기)
=> [익조] 20220919 "프로그래머스 - 셔틀 버스" 풀이 제출

익조/20220820.java
+ 처음에는 `백트래킹`으로 접근했었습니다. 명령어 입력에 대한 조합의 수를 첫째 자리부터 100 자리(임의로 둔 것)까지 일일이 백트래킹을 해주면서 타겟 숫자와 동일해지는 순간 해당 명령어를 출력시켜주도록 했습니다. 결과는 시간 초과... 😅
+ 백트래킹 시 고려하지 못했었던 부분이 있었는데, 바로 `방문처리` 부분이었습니다. 단순히 모든 경우의 수를 조합해준다는 생각만해서 방문처리를 하지 않았었는데, L과 R 명령어 사이에 일종의 `순환`이 발생해서 불필요한 탐색이 더 늘어나는 것이 문제였습니다.
+ 그리하여 동일한 숫자는 다시 방문하지 않도록 0 ~ 9999 숫자에 대해 방문처리를 해주도록 했고, 타겟 숫자에 맞춰주도록 하기 위한 가장 적은 명령어를 탐색하기에는 깊이 우선 탐색 보다 `너비 우선 탐색이` 더 적합하다고 생각했습니다.
+ 너비우선탐색으로 접근하여 나름대로 이 정도면 됐다 했는데, `런타임 에러`라는 왜맞틀에 빠지게 되었습니다.
+ 결론적으로 런타임 에러의 원인은 L과 R 연산에 대한 부분인 것으로 보입니다.
+ 저 같은 경우 처음에 L과 R 연산을 할 때 무식하게 해당 숫자를 문자로 변환시키고 자리를 조정하여 다시 숫자로 변환시키는 작업을 처리해주도록 했었는데, 이러한 작업으로 인해 메모리 관련 에러가 아닐까 했습니다.
```Java
private static int l(int number) {
char[] n = getDigits(number);
char[] newNumber = new char[4];
newNumber[0] = n[1];
newNumber[1] = n[2]; …
```
=> [익조] 20220820 "백준 - DSLR" 풀이 제출

익조/20220818.java
+ 리스트 자료구조를 캐시용 메모리로 사용했습니다.
+ 주어진 도시이름 데이터를 순회하면서  소문자로 변환한 후 해당 데이터가 기존 리스트에 있는 경우 실행시간을 1 추가 시켜주고, 없는 경우 5 추가 시켜주었습니다.
+ 이때 캐시 히트인 경우, 해당 데이터를 리스트 맨 위로 올려주었고, 캐시 미스인 경우, 우선 캐시 용량이 꽉찬 경우에 한하여 가장 하단에 있는 데이터를 삭제한 후 해당 데이터를 캐시에 추가시켜주었습니다.
O(N)
=> [익조] 20220818 "프로그래머스 - 1차 캐시" 풀이 제출 

익조/20220806.java
앗.. 최근에 풀었던 문제네요...😅 BFS를 통해 간단하게 해결할 수 있었습니다!
+ https://ikjo.tistory.com/86
=> [익조] 20220806 "프로그래머스 - 게임 맵 최단거리" 풀이 제출

익조/20220523.java
+ 브루트포스, BFS, DFS를 활용하여 해결했습니다.
+ 우선 땅의 높이 정보가 주어지면 강수량 0(비가 안 온 경우) ~ 100(대지의 최대 높이는 100이닌까) 모든 경우에 대해 안전 영역을 구하도록 했습니다.
+ 이때 대지가 물에 잠긴 것을 표시하기 위해 땅의 높이 정보인 int형 2차원 배열을 탐색하도록 했습니다. 이때 boolean 2차원 배열을 통해 특정 노드에서의 값이 강수량 미만이라면 해당 물이 잠겼다는 것을 별도로 boolean 값으로 나타냈습니다.
+ 앞서 물이 잠긴 정보를 저장한 boolean 2차원 배열을 DFS를 활용하여 안전 영역의 개수를 구하도록 했습니다.
+ 위 작업들을 반복하면서 안전 영역의 최대 개수를 구합니다.
=>  [익조] 20220523 "백준 - 안전 영역" 풀이 제출

후/20221206_1.java
=> 🔀 [후] 20221206 "구름 - 소수 찾기" 풀이 제출

후/20221024.java
각 좌표별로 상, 하, 좌, 우로 방문 여부를 가지고 있도록 Point 클래스를 정의하였습니다.
커맨드(U, D, R, L)별로 이동가능여부(좌표를 벗어나진 않는지) 확인한 후,
방문한 적이 없는 새로운 길이라면 answer++를 해주고,
좌표를 이동시켰습니다.
O(N), N: dir.length
=> 🔀 [후] 20221024 "프로그래머스 - 방문 길이" 풀이 제출

익조/20220803.java
접근 방법을 기술 블로그에 정리해보았습니다 ㅎㅎ
+ https://ikjo.tistory.com/301
=> [익조] 20220803 "백준 - 부분합" 풀이 제출

익조/20220729.java
접근 방법을 기술 블로그에 별도 정리해보았습니다 ㅎㅎ
+ https://ikjo.tistory.com/295
=> [익조] 20220729 "프로그래머스 - 교점에 별 만들기" 풀이 제출

익조/20220728.java
+ 문제를 보고 전형적인 다이나믹 프로그래밍 문제라고 느낌이 왔습니다.
+ 어떻게 메모이제이션을 할 수 있을까 고민하던 중 그림으로 한번 그려보다가 아이디어를 떠올렸습니다.
> <img src="https://user-images.githubusercontent.com/82401504/181507972-37dc8cde-7795-4953-ae3c-be023de0c465.png" width="400" height="200">
+ 위 그림을 통해 다음과 같은 사실을 알 수 있었습니다.
+ 세 개의 칸 중 왼쪽 칸의 값은 `바로 위 칸의 값`과 `그 오른쪽 칸의 값`에만 의존적입니다.
+ 세 개의 칸 중 가운데 칸의 값은 `위에 있는 세 개의 칸 값`에 의존적입니다.
+ 마지막으로, 세 개의 칸 중 오른쪽 칸의 값은 `바로 위 칸의 값`과 `그 왼쪽 칸의 값`에만 의존적입니다.
+ 따라서 각 경로의 합의 최댓값과 최솟값을 구함에 있어 두 종류의 메모제이션을 통해 다음과 같은 식의 로직을 작성할 수 있었습니다.
```java
for (int i = 1; i < n; i++) {
maxMemo[i][0] = Math.max(maxMemo[i-1][0], maxMemo[i-1][1]) + board[i][0];
maxMemo[i][1] = Math.max(maxMemo[i-1][0], Math.max(maxMemo[i-1][1], maxMemo[i-1][2])) + board[i][1];
maxMemo[i][2] = Math.max(maxMemo[i-1][1], maxMemo[i-1][2]) + board[i][2]; …
```
=> [익조] 20220728 "백준 - 내려가기" 풀이 제출 

익조/20220701.java
+ 으악 어려웠습니다. 처음에 완전 탐색으로 푸는 줄 알고 완전 탐색으로 접근했다가 시간초과 뜨고...
+ 어떻게 푸는거지...하다가 결국 밑에 알고리즘 분류를 들쳐보면서 DP 문제라는 것을 알았습니다..ㅋㅋ
+ 하지만 DP로 푸는데도 나름대로 규칙성을 세워 구해보고자 했으나... 긴 삽질 과정을 통해 제가 세운 규칙성이 올바르지 않다는 것을 깨닫고 결국 풀이를 보게 되었습니다... 😂
+ 완전 탐색 풀이(시간 초과)
```Java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
class Main {
static int n, sum;
static int[][] stickers;
static int[] dx = {0, 0, 1, -1}, dy = {1, -1, 0, 0};
static boolean[][] detached;
public static void main(String[] args) throws IOException {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
StringTokenizer st;
int t = Integer.parseInt(br.readLine());
for (int i = 0; i < t; i++) {
n = Integer.parseInt(br.readLine());
stickers = new int[2][n]; …
```
=> [익조] 20220701 "백준 - 스티커" 풀이 제출 

익조/20220623.java
+ 2차원 배열을 통해 연결된 컴퓨터 각각의 쌍을 나타내도록 했습니다.
+ ex. 1 -> 2 연결 : array[1][2] = 1
+ 또한 감염된 컴퓨터를 나타내도록 컴퓨터 개수만큼의 1차원 배열을 선언했습니다.
+ 첫번째 컴퓨터 1과 연결된 노드를 탐색하고 발견 시 해당 노드를 출발 노드로 생각하여 다시 앞선 작업을 반복해주었습니다.
+ 반복 동일 탐색을 막기 위해 방문처리를 별도로 해주었습니다.
+ (삽질했었던 부분) 처음 출발 노드가 1인데, 이때 1 -> 2, 1 -> 3, ... 이런 것만 1과 연결된 게 아니라 2 -> 1, 3 -> 1, ... 이런 것도 1과 연결된 것으로 볼 수 있으므로 이에 대한 탐색도 추가적으로 해주었습니다.
=> [익조] 20220623 "백준 - 바이러스" 풀이 제출

익조/20220619.java
+ 처음 접근 방법은 "정렬"을 통해 최적의 해를 구할 수 있는 상태를 만든 후 정답(유저가 탐험할 수 있는 던전 개수)을 구하는 방법을 생각해봤으나(일종의 그리디?) 이리저리 정렬해봐도 어떻게 정렬해야할지 감이 안왔습니다.
+ 그리하여 던전을 탐험할 수 있는 모든 경우의 수를 탐색하여 정답을 구하고자 했습니다.
+ 해당 문제에서는 "순서"도 중요하기 때문에 조합이 아닌 "순열"을 구할 필요가 있었습니다.
+ 앞선 로또, 메뉴 리뉴얼 등 조합을 구하는 문제와 비슷하면서도 다른 결의 문제
+ 순열을 구해보는 것은 처음이라 기술 블로그에서 자바를 통해 순열을 구하는 여러 방법들을 찾아보았습니다.
+ 찾아본 방법은 swap과 dfs를 이용한 방법이었습니다.
+ 먼저 swap를 이용하여 순열을 구해보았으나, 19개 테스트 중 2개의 테스트가 자꾸 오류나 결국 dfs를 이용하여 문제를 해결할 수 있었습니다.
+ 문제를 풀면서 삽질을 많이 했었는데, dfs를 이용한 탐색은 (관습적으로?) 종료 조건이 있어야 한다고 생각했었기 떄문이었습니다. 😂
+ 삽질의 주 원인은 백트래킹으로 탐색하면서 탐색할 수 있는 최대 depth까지 탐색했을 때를 종료 조건(return 문)으로 둔 것 때문이었습니다.
+ 방문 처리를 하기 때문에 종료 조건이 없어도 무한 재귀 없이 완전 탐색을 마칠 수 있었습니다.
+ https://minhamina.tistory.com/37?category=837168
=> [익조] 20220619 "프로그래머스 - 피로도" 풀이 제출

익조/20220613.java
+ 해당 문제는 BFS를 통해 해결할 수 있었습니다.
+ 해당 문제에서는 (N, M)까지의 최단 거리를 구해야하는데 BFS 탐색 시 (N, M) 지점에 도착할 때마다 걸린 거리를 비교하여 최단 거리를 구하도록 합니다.(Math.min() 활용)
+ 이때, 최악의 경우 (1, 1) 지점에서 (N, M)까지 걸리는 거리는 최대 100 * 100 만큼이 소요되므로 최초 비교 값을 10000으로 설정해둡니다.
=> [익조] 20220613 "백준 - 미로 찾기" 풀이 제출

익조/20220609.java
+ 주어진 영단어 문자열 순서대로 첫 번째 단어의 마지막 글자와 그 다음 단어의 첫 글자를 비교하도록 했습니다.
+ 이때 다음 단어로 업데이트 될 때마다 플레이어 번호는 1~n으로 로테이션 되도록했고 한번 로테이션이 끝나면 턴수를 1 증가하도록 했습니다.
+ 이때 중복되는 단어를 말하면 안되므로 별도로 map을 만들어주어 중복체크를 해주도록 했습니다.
+ 아무도 틀리지 않은 경우를 별도 boolean형 변수로 구분하였고 이 경우 {0, 0}을 반환해주도록 했습니다.
O(N)
=> [익조] 20220609 "프로그래머스 - 영어 끝말 잇기" 풀이 제출

익조/20220607.java
처음에는 단순 무식하게 주어진 구간 즉, 시작 인덱스와 끝 인덱스간 합을 일일이 for문으로 직접더해주었습니다. 결과는 예상했지만 시간 초과..ㅎㅎ 뭔가 다른 방식으로 구간합을 구해야겠다는 생각이 들었고 뭔가 경험상(?) 주어진 수들을 인덱스별로 누적하여 더해줘야겠다는 생각을 해보았습니다. 이러한 수의 배열을 통해 주어진 예시의 답을 어떻게 구할지 고민해보았고 방금 전 구한 누적 배열에서 끝 인덱스의 값에서 시작 인덱스 보다 1 적은 인덱스의 값을 빼주면 구간 합이 나오는 것을 확인할 수 있었습니다.
O(N)
=> [익조] 20220607 "백준 - 구간 합 구하기 4" 풀이 제출

익조/20220603.java
처음에 우선순위 큐를 이용하려다가 poll 연산으로 인해 내부 순서가 뒤죽 박죽되서 결국에는 List를 이용하여 데이터를 넣고 뺄 때마다 매번 정렬해주도록 했습니다.  시간 제한에 걸리지 않을까 싶었는데 생각보다 여유있게 통과되네요..💦 (액자의 크기가 최대 20이므로 정렬 시 시간 복잡도가 크리티컬하지 않았던 것 같습니다.)
https://ikjo.tistory.com/249
Why priority queue re-order element when I do poll()?
https://stackoverflow.com/questions/64288709/why-priority-queue-re-order-element-when-i-do-poll
예전에도 우선순위 큐 쓰다가 poll로 인해 내부 순서가 뒤 바뀌는 일이 있었는데, 이번에 다시금 상기해봅니다..ㅋㅋ
=> [익조] 20220603 "백준 - 후보 추천하기" 풀이 제출

익조/20220530.java
듣지 못한 사람들을 해시맵으로 저장하고 이후 보지 못한 사람들을 입력받을 때 해시맵의 containsKey 메서드를 이용하여 듣보잡의 사람들을 구하도록 했습니다.
O(N)
=>  [익조] 20220530 "백준 - 듣보잡" 풀이 제출

익조/20220526.java
에공.. 이번 문제 저번주 금요일에 풀었었던 문제이군요..ㅋㅋ 저번 주에 기술 블로그에 제 풀이를 복기해보았습니다. 개인적으로 꽤나 애먹었던 문제였습니다.
기술블로그 : https://ikjo.tistory.com/237
=> [익조] 20220526 프로그래머스 - 다리를 지나는 트럭

익조/20220718.java
+ 우선 전위 순회(루트-왼쪽-오른쪽)한 결과만으로 이진 트리 구조를 만드는 것이 급선무였습니다.
+ 이진 트리 구조는 자식 노드를 추가할 때 부모 노드를 기준으로 작으면 왼쪽에, 크면 오른쪽에 배치하는 것이었습니다.
+ 이러한 특성을 이용하여 주어진 수를 최초 `루트 노드`와 비교하면서 왼쪽, 오른쪽을 탐색하면서 트리 구조를 이루도록 했는데, 이때 노드라는 `별도의 구조체`를 만들고 또한 `재귀`를 사용했습니다.
+ 후위 순회는 가장 왼쪽 하단 노드에서 출발하여 `왼쪽 - 오른쪽  - 상위 노드` 순으로 순회하는 것으로서 별도의 재귀함수를 이용하여 구현할 수 있었습니다.
아래 기술 블로그의 "자바를 통한 트리 개념 정리 및 구현" 자료를 참고하였는데, 이게 정말 많은 도움이 되었습니다!
https://readerr.tistory.com/35
=> [익조] 20220718 "백준 - 이진 검색 트리" 풀이 제출

익조/20220714.java
+ 아오.. 순열로 푸는 건 줄 알고 순열로 계속하면서 나름대로 최적화해봐도 시간초과....
+ 맞왜틀의 늪에 빠져있다가 근본적으로 뭐가 잘못됐는지 살피다가 순열로 탐색 시 불필요한(중복된) 경우의 수를 계속 따지고 있었습니다.
+ 뒤늦게 정신차리고 조합으로 바꾸어서 해결할 수 있었습니다.
```Java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import java.util.StringTokenizer;
class Main {
static int result = 1000, n;
static int[][] abilities;
static Stack<Integer> players = new Stack<>();
public static void main(String[] args) throws IOException {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
n = Integer.parseInt(br.readLine());
abilities = new int[n + 1][n + 1];
StringTokenizer st;
for (int i = 1; i < n + 1; i++) {
st = new StringTokenizer(br.readLine());
for (int j …
```
=> [익조] 20220714 "백준 - 스타트와 링크" 풀이 제출

익조/20220707.java
+ BFS를 통해 풀 수 있었습니다.
+ 주어진 대기실 정보에서 응시자가 있는 위치(P)를 시작점으로 두어 인근 타 응시자와의 거리가 2 이하인지를 검증하도록 했습니다.
=> [익조] 20220707 "프로그래머스 - 거리두기 확인하기" 풀이 제출

익조/20220706.java
+ 메모리 제한이 512MB인 점이 마음에 걸렸지만, 알고있는 접근 방법이 백트래킹(with dfs)을 통한 각각의 경우의 수를 탐색하는 방법밖에 없기에 백트래킹으로 풀이해보았지만 예상대로 시간초과...
+ 메모리 제한이 넉넉한 거 보니 + 시간이 빠듯한 거보니 DP를 예상해보았지만, 도무지 어떻게 푸는지 감이 안 와 결국 기술 블로그를 뒤적였습니다...🤣
+ 배낭 문제, 냅색 알고리즘이라는 방법을 처음 알게 되었고, "오..."하면서 접근 방법을 학습했습니다. 솔직히 아직 익숙친 않아서 앞으로 많은 연습이 필요해보입니다. 😂
+ 직접 풀진 못했지만 새로운 접근 방법을 배울 수 있어 유익했습니다! 🎉
+ 백트래킹 풀이(시간초과)
```Java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
class Main {
static int n, k, result;
static int[] weights, values;
public static void main(String[] args) throws IOException {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
StringTokenizer st = new StringTokenizer(br.readLine());
n = Integer.parseInt(st.nextToken());
k = …
```
=> [익조] 20220706 "백준 - 평범한 배낭" 풀이 제출
